# Data Wrangling

In [1]:
import os
import re
import datetime as dt
from time import time
import random
import math
import html

# data science
import numpy as np
import pandas as pd

In [2]:
# configurations

# Allow multiple outputs for each cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# Suppress warnings 
import warnings
warnings.filterwarnings('ignore')

# display all columns
pd.set_option('display.max_columns', None)

# suppress auto-conversion to scientific notation
pd.set_option('display.precision', 6)

# Tweets

Source: https://data.world/balexturner/390-000-metoo-tweets<br>
390,000 tweets under the #MeToo hashtag dated between November 29th and December 25th, 2017

In [3]:
# read tweets
df = pd.read_excel('Data/metoo_tweets_dec2017.xlsx')

In [4]:
df.columns

Index(['text', 'favorited', 'favoriteCount', 'replyToSN', 'created',
       'truncated', 'replyToSID', 'id', 'replyToUID', 'statusSource',
       'screenName', 'retweetCount', 'isRetweet', 'retweeted', 'longitude',
       'latitude'],
      dtype='object')

In [5]:
# 393135 rows, 16 columns
df.shape

(393135, 16)

In [6]:
df.describe(include='all')

text favorited  \
count                                              393135    393135   
unique                                             192901         1   
top     RT @LaurenJauregui: Shout out to all the stron...     False   
freq                                                 5443    393135   
first                                                 NaN       NaN   
last                                                  NaN       NaN   
mean                                                  NaN       NaN   
std                                                   NaN       NaN   
min                                                   NaN       NaN   
25%                                                   NaN       NaN   
50%                                                   NaN       NaN   
75%                                                   NaN       NaN   
max                                                   NaN       NaN   

        favoriteCount        replyToSN              created truncated  \
count   393135.000000            49716               393135    393135   
unique            NaN            20300                30196         2   
top               NaN  realDonaldTrump  2017-12-16 13:53:00     False   
freq              NaN             2062                  713    305538   
first             NaN              NaN  2017-11-29 13:52:00       NaN   
last              NaN              NaN  2017-12-25 23:59:00       NaN   
mean         3.311494              NaN                  NaN       NaN   
std        142.558537              NaN                  NaN       NaN   
min          0.000000              NaN                  NaN       NaN   
25%          0.000000              NaN                  NaN       NaN   
50%          0.000000              NaN                  NaN       NaN   
75%          0.000000              NaN                  NaN       NaN   
max      45922.000000              NaN                  NaN       NaN   

          replyToSID            id    replyToUID  \
count   4.190500e+04  3.931350e+05  4.971800e+04   
unique           NaN           NaN           NaN   
top              NaN           NaN           NaN   
freq             NaN           NaN           NaN   
first            NaN           NaN           NaN   
last             NaN           NaN           NaN   
mean    9.398637e+17  9.408284e+17  1.228446e+17   
std     1.778519e+16  2.292175e+15  2.965066e+17   
min     2.410985e+09  9.360000e+17  1.200000e+01   
25%     9.388620e+17  9.390000e+17  2.397010e+07   
50%     9.407080e+17  9.408860e+17  1.323453e+08   
75%     9.425940e+17  9.426210e+17  1.672785e+09   
max     9.454390e+17  9.454440e+17  9.451420e+17   

                                             statusSource      screenName  \
count                                              393132          393135   
unique                                               1695          222311   
top     <a href="http://twitter.com/download/iphone" r...  DulleyTopBooks   
freq                                               127447             790   
first                                                 NaN             NaN   
last                                                  NaN             NaN   
mean                                                  NaN             NaN   
std                                                   NaN             NaN   
min                                                   NaN             NaN   
25%                                                   NaN             NaN   
50%                                                   NaN             NaN   
75%                                                   NaN             NaN   
max                                                   NaN             NaN   

         retweetCount isRetweet retweeted   longitude    latitude  
count   393135.000000    393135    393135  123.000000  123.000000  
unique            NaN         2         1         NaN         NaN  
top               NaN  

In [7]:
df['screenName'].nunique()

222311

In [8]:
df['id'].nunique()

5642

In [9]:
df.columns

Index(['text', 'favorited', 'favoriteCount', 'replyToSN', 'created',
       'truncated', 'replyToSID', 'id', 'replyToUID', 'statusSource',
       'screenName', 'retweetCount', 'isRetweet', 'retweeted', 'longitude',
       'latitude'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 393135 entries, 1 to 393135
Data columns (total 16 columns):
text             393135 non-null object
favorited        393135 non-null bool
favoriteCount    393135 non-null int64
replyToSN        49716 non-null object
created          393135 non-null datetime64[ns]
truncated        393135 non-null bool
replyToSID       41905 non-null float64
id               393135 non-null int64
replyToUID       49718 non-null float64
statusSource     393132 non-null object
screenName       393135 non-null object
retweetCount     393135 non-null int64
isRetweet        393135 non-null bool
retweeted        393135 non-null bool
longitude        123 non-null float64
latitude         123 non-null float64
dtypes: bool(4), datetime64[ns](1), float64(4), int64(3), object(4)
memory usage: 40.5+ MB


In [11]:
df.isnull().sum()
# will look into 'replyToSID', 'id', 'replyToUID', 'replyToSN'

text                  0
favorited             0
favoriteCount         0
replyToSN        343419
created               0
truncated             0
replyToSID       351230
id                    0
replyToUID       343417
statusSource          3
screenName            0
retweetCount          0
isRetweet             0
retweeted             0
longitude        393012
latitude         393012
dtype: int64

First, let's check 'replyToSID', 'id', 'replyToUID'

In [12]:
df[['replyToSID', 'id', 'replyToUID']]

replyToSID                  id    replyToUID
1                NaN  936000000000000000           NaN
2                NaN  936000000000000000  2.661498e+08
3                NaN  936000000000000000           NaN
4                NaN  936000000000000000           NaN
5                NaN  936000000000000000           NaN
6                NaN  936000000000000000           NaN
7                NaN  936000000000000000           NaN
8                NaN  936000000000000000           NaN
9       9.360000e+17  936000000000000000  4.969813e+07
10      9.360000e+17  936000000000000000  5.892869e+07
11               NaN  936000000000000000           NaN
12               NaN  936000000000000000           NaN
13      9.360000e+17  936000000000000000  2.970462e+09
14               NaN  936000000000000000           NaN
15               NaN  936000000000000000           NaN
16               NaN  936000000000000000           NaN
17               NaN  936000000000000000           NaN
18               NaN  936000000000000000           NaN
19               NaN  936000000000000000           NaN
20               NaN  936000000000000000           NaN
21               NaN  936000000000000000           NaN
22      9.360000e+17  936000000000000000  7.592510e+05
23      9.360000e+17  936000000000000000  2.088223e+08
24               NaN  936000000000000000           NaN
25               NaN  936000000000000000  2.507388e+07
26               NaN  936000000000000000           NaN
27               NaN  936000000000000000           NaN
28               NaN  936000000000000000           NaN
29               NaN  936000000000000000           NaN
30               NaN  936000000000000000           NaN
...              ...                 ...           ...
393106           NaN  945083000000000000           NaN
393107           NaN  945083000000000000           NaN
393108           NaN  945083000000000000           NaN
393109           NaN  945083000000000000           NaN
393110           NaN  945083000000000000           NaN
393111           NaN  945083000000000000           NaN
393112  9.450700e+17  945082000000000000  2.194904e+07
393113           NaN  945082000000000000           NaN
393114           NaN  945082000000000000           NaN
393115           NaN  945082000000000000           NaN
393116           NaN  945082000000000000           NaN
393117           NaN  945082000000000000           NaN
393118           NaN  945082000000000000           NaN
393119           NaN  945082000000000000           NaN
393120           NaN  945082000000000000           NaN
393121           NaN  945082000000000000  5.947103e+07
393122           NaN  945082000000000000           NaN
393123           NaN  945082000000000000           NaN
393124           NaN  945082000000000000           NaN
393125           NaN  945082000000000000           NaN
393126           NaN  945082000000000000           NaN
393127           NaN  945082000000000000           NaN
393128           NaN  945082000000000000           NaN
393129           NaN  945082000000000000           NaN
393130           NaN  945082000000000000           NaN
393131           NaN  945082000000000000           NaN
393132           NaN  945082000000000000           NaN
393133           NaN  945082000000000000           NaN
393134           NaN  945082000000000000           NaN
393135           NaN  945082000000000000           NaN

[393135 rows x 3 columns]

replyToUID has too many missing values. Will drop.

In [13]:
# the 'id' field is not unique (cannot be used to uniquely identify a tweet)
# will drop and create new id
df['id'].nunique() == len(df)

False

In [14]:
# interesting, I'll keep this column
df['replyToSN'].value_counts()

realDonaldTrump    2062
Alyssa_Milano       746
SenGillibrand       662
rosemcgowan         511
TIME                435
thehill             374
SenFranken          313
CNN                 308
FoxNews             271
morningmika         225
funder              221
nytimes             185
benshapiro          184
MiraSorvino         183
Rosie               183
BetteMidler         180
jaketapper          170
MSNBC               168
StaciaRR            152
yashar              148
washingtonpost      145
salmahayek          137
EdanClay            136
EzraFitz_13         132
Morning_Joe         130
Amy_Siskind         128
NBCNews             128
politico            122
krassenstein        119
terrycrews          117
                   ... 
salonpas              1
heatheroverhere       1
Aetna                 1
elmtree916            1
rychemom              1
Real_Infinity95       1
sndorf                1
EricMcCormack         1
NorwellDemocrat       1
deelymac              1
tweetangelarose 

In [15]:
df
# I hope the tweets aren't truncated.. Let's check

text  favorited  \
1         American Harem.. #MeToo https://t.co/HjExLJdGuF      False   
2       @johnconyersjr  @alfranken  why have you guys ...      False   
3       Watched Megan Kelly ask Joe Keery this A.M. if...      False   
4       Women have been talking about this crap the en...      False   
5       .@BetteMidler please speak to this sexual assa...      False   
6       We can't keep turning a blind eye and pretend ...      False   
7       Jay-Z is saying what I've been saying. DJT's j...      False   
8       Where in the world is @MattLauer Celebrate #MeToo      False   
9              @JoyAnnReid Keep it coming ladies!  #MeToo      False   
10      @RepAdamSmith Workplace is one place, but what...      False   
11      Is it just me or does the #MeToo &lt;----icon;...      False   
12      Just  got scammed out of  $25.  Bought #TigerW...      False   
13      @RepKathleenRice @RepJayapal Calling out @RepJ...      False   
14                   #BlackLivesMatter with #MeToo yup ok      False   
15      Why are not the men haters from #Metoo marchin...      False   
16      I was sexually harassed as a "young Intern" fo...      False   
17      So I have a question. This post was published ...      False   
18      Im pretty sure @DanRather and Brian Williams a...      False   
19      Aint trying to start nothing but wouldnt it be...      False   
20      How can @realDonaldTrump talk about anyone tha...      False   
21      Yes!! WHEN it happens to you, THEN you can dec...      False   
22      @CNN Read: "we must destroy the oppressive pat...      False   
23      @SaveUSA1776 Until I learned he did, I don't l...      False   
24      men all over this country are seeking ways to ...      False   
25      @RealDonaldTrump How Much Did @JakeTapper thet...      False   
26      Geraldo Rivera says "news is a flirty business...      False   
27      Political men: it is only a matter of time. #M...      False   
28      How do you reconcile your love of someone if t...      False   
29      I was patting my cat when she left my laps sud...      False   
30      Kathleen Kane: The Rise and Fall | Philadelphi...      False   
...                                                   ...        ...   
393106  RT @_JustGee_: With the attacks on Matt Damon ...      False   
393107  RT @pewdrdad: Chief Justice John Roberts order...      False   
393108  RT @LauraLoomer: I was at the mall and a man s...      False   
393109  I am reassessing what the fuck I am being told...      False   
393110  RT @SteveBannen: Hay #MeToo, I thought you mig...      False   
393111  ‚Ä¢ Before #metoo there was Clara Shortridge F...      False   
393112  @VanillaLady @starsetonline #metoo ... Wait......      False   
393113  My bro claims #metoo is just a witchhunt and r...      False   
393114  RT @WithoutViolence: #MeToo creator will push ...      False   
393115  RT @Microsoft: Microsoft president @BradSmi of...      False   
393116  Chief Justice John Roberts orders misconduct r...      False   
393117  RT @raju: The Perils of Publicly Saying #MeToo...      False   
393118  RT @SteveBannen: Hay #MeToo, I thought you mig...      False   
393119  RT @LauraLoomer: I was at the mall and a man s...      False   
393120  RT @peaceandjoy101: Sadly, we are now at a poi...      False   
393121  @Jaguars need to start tweeting #MeToo after t...      False   
393122  RT @MzCSmith: The #MeToo movement comes to spo...      False   
393123  RT @SteveBannen: Hay #MeToo, I thought you mig...      False   
393124  RT @NevadaJack2: Chief Justice John Roberts or...      False   
393125  What Microsoft learned from our #MeToo moment ...      False   
393126  RT @YousefMunayyer: Shocking that in this #MeT...      False   
393127  RT @Suffragentleman: You can only choose one.....      False   
393128  RT @SteveBannen: Hay #MeToo, I thought you mig...      False   
393129  RT @TianaTheFirst: If you don't believe our cu...      False   
393130  RT @LauraLoom

In [16]:
df.iloc[[2]]
df.iloc[[2]]['text']
# Damn.. it's truncated. Let's see how many are truncated.

text  favorited  \
3  Watched Megan Kelly ask Joe Keery this A.M. if...      False   

   favoriteCount replyToSN             created  truncated  replyToSID  \
3              0       NaN 2017-11-29 23:59:00       True         NaN   

                   id  replyToUID  \
3  936000000000000000         NaN   

                                        statusSource      screenName  \
3  <a href="http://twitter.com/download/android" ...  DemerisePotvin   

   retweetCount  isRetweet  retweeted  longitude  latitude  
3             0      False      False        NaN       NaN

3    Watched Megan Kelly ask Joe Keery this A.M. if...
Name: text, dtype: object

In [17]:
df['truncated'].value_counts(dropna=False)

False    305538
True      87597
Name: truncated, dtype: int64

In [18]:
87597 / (305538 + 87597)
# Roughly 22% of tweets are truncated. I can work with that.

0.22281658972108817

In [19]:
# make sure tweets contain the #metoo hashtag
df['text'].str.contains('#metoo', case=False).value_counts()

True     338554
False     54581
Name: text, dtype: int64

In [20]:
# 54,581 out of 393,135 tweets do not contain the #metoo hashtag (case insensitive)
# but it appears as though the tweets without #metoo are also discussing relevant topic
# therefore will not drop these tweets - for now
df[df['text'].str.contains('#metoo', case=False) == False]

text  favorited  \
3       Watched Megan Kelly ask Joe Keery this A.M. if...      False   
10      @RepAdamSmith Workplace is one place, but what...      False   
12      Just  got scammed out of  $25.  Bought #TigerW...      False   
13      @RepKathleenRice @RepJayapal Calling out @RepJ...      False   
16      I was sexually harassed as a "young Intern" fo...      False   
17      So I have a question. This post was published ...      False   
18      Im pretty sure @DanRather and Brian Williams a...      False   
20      How can @realDonaldTrump talk about anyone tha...      False   
21      Yes!! WHEN it happens to you, THEN you can dec...      False   
24      men all over this country are seeking ways to ...      False   
25      @RealDonaldTrump How Much Did @JakeTapper thet...      False   
28      How do you reconcile your love of someone if t...      False   
33      And @headhntr freaking CONFESSED online last w...      False   
34      The bad behavior getting exposed in Hollywood ...      False   
35      8. But how soon before this snowball of sexual...      False   
40      g-d bless every brave woman who is standing up...      False   
42      Matt Lauer has always made my skin crawl. #NoS...      False   
44      Insteading of saying "oh no! I'm so sad blank ...      False   
47      Thinking of @AnnCurry and the unpleasantness M...      False   
51      When I did it, I knew for sure, that I would b...      False   
53      Yet #fakemedia &amp; #Hollywood wants to use #...      False   
55      @Alyssa_Milano It took me almost 30 years and ...      False   
57      @Soros_Antifa @KimJung59597672 @MaineAntifa @A...      False   
58      @GeraldoRivera @MLauer As the co-host of NBCs ...      False   
59      Sadly, it seems that most men in power abuse i...      False   
61      Given the sexual harassment pandemic, I have t...      False   
63      A MUST READ Roy Moore co-authored legal course...      False   
69      @heierup Is what @GeraldoRivera saying is that...      False   
71      You cant say you are supporting a victim of se...      False   
75      Women who have been sexual assaulted/harassed ...      False   
...                                                   ...        ...   
392822  @RobbysRamblings @babzylonia @jbwr2300 @filipe...      False   
392837  @Real_Dan_Joseph @WeWuzMetokur I don't want to...      False   
392841  @sherandnolan Ì†ΩÌ±ãÌ†ΩÌ±ã\r"Donald's not goin...      False   
392843  @VeganYogaDude Would be great except she went ...      False   
392861  All I want for Christmas is a president who is...      False   
392866  8 maids a milking\r4 Trumps a bilking\r  #Impe...      False   
392878  @Auroraknite @babzylonia @jbwr2300 @filipepw @...      False   
392900  @nytimes Sounds like sexual harassment by nyt....      False   
392901  My husband encouraged me to wrap presents with...      False   
392908  @writerincanada @bjportraits Women are talking...      False   
392913  25K Sign Petition Calling for Matt Damon's Rem...      False   
392944  @cenkuygur Your hardly independent when you ta...      False   
392947  @Auroraknite @RobbysRamblings @jbwr2300 @filip...      False   
392957  @nytimes Didn't create it. Sexual allegations ...      False   
392961  While the American Purity Police sets a new pe...      False   
392962  @Cleverestcookie You too Cathy. Just finished ...      False   
392970  So this is where we are\rIt's not where we had...      False   
392978  @joyellen1962 @t_labin @HumanistReport Words a...      False   
392985  #BREAKING #NEWS\r\rUnbelievable 2 see crooked ...      False   
392995  Before Santa was smooching with Ronnie Ronette...      False   
393010  It‚Äôs sad that it still takes bravery to figh...      False   
393025  ‚ú®‚ú®Do you want to know what Bagging Nuts Ì†...      False   
393038  Remember @HardballChris's outrage over @realDo...      False   
393041  Watch political consultant &amp; our founder M...      False   
393044  It never happ

In [21]:
# before exporting, I'm going to assign unique IDs and drop unnecessary columns
df['tweetId'] = np.arange(1, len(df)+1)
df.drop(['id', 'replyToSID','replyToUID'],1,inplace=True)

# reorganize the columns
cols = ['tweetId', 'screenName', 'text', 'replyToSN', 'isRetweet',
        'retweeted', 'retweetCount', 'favorited', 'favoriteCount',
        'truncated', 'created', 'statusSource', 'longitude', 'latitude']

df = df[cols]
df

tweetId       screenName  \
1             1        ahmediaTV   
2             2   JesusPrepper74   
3             3   DemerisePotvin   
4             4     TheDawnStott   
5             5   scottygirl2014   
6             6     ForEverBrenn   
7             7   silveriaalison   
8             8         calrican   
9             9   traugott_sarah   
10           10  SchifanoRaelene   
11           11      BrunusCutis   
12           12       RDonSteele   
13           13     _standeliver   
14           14         dbehan79   
15           15       european_4   
16           16  FrancescaBiller   
17           17   emilyjoypoetry   
18           18         frozenjo   
19           19         num1_fan   
20           20      DougsMom204   
21           21         page_lie   
22           22  VirginiusPrimus   
23           23       1mimi4ever   
24           24      justshocked   
25           25    ProphetPhella   
26           26   womanontheleft   
27           27        JessLivMo   
28           28          JC4ever   
29           29       european_4   
30           30  collegeclasses5   
...         ...              ...   
393106   393106   writerincanada   
393107   393107    ellimayradrep   
393108   393108  viniciusnikolod   
393109   393109      JamesEFinch   
393110   393110         nscrowba   
393111   393111       book_tribe   
393112   393112         jp_flyer   
393113   393113       ruby_wine_   
393114   393114      DebraRobbin   
393115   393115      StevenGuggs   
393116   393116      PeterFeaman   
393117   393117  Tucs0nMortgages   
393118   393118  tlacovaspravask   
393119   393119      King17Larry   
393120   393120         Rparisee   
393121   393121        Adam_Eire   
393122   393122   mikefreemanNFL   
393123   393123        tomcat159   
393124   393124     Zwoodbutcher   
393125   393125        EINITNews   
393126   393126   AlgerianPalest   
393127   393127    kingofponders   
393128   393128      KosPatricia   
393129   393129     TwittaChicca   
393130   393130   BuffyLibSlayer   
393131   393131       boaomega22   
393132   393132   April_Magazine   
393133   393133         Noofer55   
393134   393134           ZBezzt   
393135   393135         pewdrdad   

                                                     text        replyToSN  \
1         American Harem.. #MeToo https://t.co/HjExLJdGuF              NaN   
2       @johnconyersjr  @alfranken  why have you guys ...    johnconyersjr   
3       Watched Megan Kelly ask Joe Keery this A.M. if...              NaN   
4       Women have been talking about this crap the en...              NaN   
5       .@BetteMidler please speak to this sexual assa...              NaN   
6       We can't keep turning a blind eye and pretend ...              NaN   
7       Jay-Z is saying what I've been saying. DJT's j...              NaN   
8       Where in the world is @MattLauer Celebrate #MeToo              NaN   
9              @JoyAnnReid Keep it coming ladies!  #MeToo       JoyAnnReid   
10      @RepAdamSmith Workplace is one place, but what...     RepAdamSmith   
11      Is it just me or does the #MeToo &lt;----icon;...              NaN   
12      Just  got scammed out of  $25.  Bought #TigerW...              NaN   
13      @RepKathleenRice @RepJayapal Calling out @RepJ...  RepKathleenRice   
14                   #BlackLivesMatter with #MeToo yup ok              NaN   
15      Why are not the men haters from #Metoo marchin...              NaN   
16      I was sexually harassed as a "young Intern" fo...              NaN   
17      So I have a question. This post was published ...              NaN   
18      Im pretty sure @DanRather and Brian Williams a...              NaN   
19      Aint trying to start nothing but wouldnt it be...              NaN   
20      How can @realDonaldTrump talk about anyone tha...              NaN   
21      Yes!! WHEN it happens to you, THEN you can dec...              NaN   
22      @CNN Read: "we must destroy the oppressive pat...  

In [22]:
df['text'].values.tolist()

['American Harem.. #MeToo https://t.co/HjExLJdGuF',
 '@johnconyersjr  @alfranken  why have you guys not resigned yet? Liberal hypocrisy! #MeToo',
 'Watched Megan Kelly ask Joe Keery this A.M. if she can "rub my fingers through your hair", and refer to his body be https://t.co/Q86wfW7DeJ',
 'Women have been talking about this crap the entire time, finally someone listened. #metoo https://t.co/JlK11yhFXc',
 '.@BetteMidler please speak to this sexual assault by @GeraldoRivera during the interview. #MeToo  https://t.co/1iuafGaOmv',
 "We can't keep turning a blind eye and pretend this isn't real. #metoo https://t.co/1dLZcftbSs",
 "Jay-Z is saying what I've been saying. DJT's jobis done. The dialogues have begun:\r racism\r#metoo \rmorality\rhum https://t.co/KJtQBEoonR",
 'Where in the world is @MattLauer Celebrate #MeToo',
 '@JoyAnnReid Keep it coming ladies!  #MeToo',
 '@RepAdamSmith Workplace is one place, but what about our HOMES?! Who protects Citizens when HOA/COA Boards &amp; Attorn h

In [23]:
# need to get rid of /r 
df['text'] = df['text'].str.replace(r'\r', ' ')
df['text'].str.contains(r'\r').value_counts()

False    393135
Name: text, dtype: int64

In [24]:
# unescape '&amp', etc
df['text'] = [html.unescape(i) for i in df['text'].values.tolist()]

In [25]:
# df.to_sql('tweets', con, if_exists='replace', index=False)
df.to_csv('Data/tweets.csv', index=False, encoding='utf-8')

# Unique Users

In [26]:
# uniqueUsers = pd.read_sql('SELECT DISTINCT screenName from tweets', con)
uniqueUsers = df.copy()
uniqueUsers

tweetId       screenName  \
1             1        ahmediaTV   
2             2   JesusPrepper74   
3             3   DemerisePotvin   
4             4     TheDawnStott   
5             5   scottygirl2014   
6             6     ForEverBrenn   
7             7   silveriaalison   
8             8         calrican   
9             9   traugott_sarah   
10           10  SchifanoRaelene   
11           11      BrunusCutis   
12           12       RDonSteele   
13           13     _standeliver   
14           14         dbehan79   
15           15       european_4   
16           16  FrancescaBiller   
17           17   emilyjoypoetry   
18           18         frozenjo   
19           19         num1_fan   
20           20      DougsMom204   
21           21         page_lie   
22           22  VirginiusPrimus   
23           23       1mimi4ever   
24           24      justshocked   
25           25    ProphetPhella   
26           26   womanontheleft   
27           27        JessLivMo   
28           28          JC4ever   
29           29       european_4   
30           30  collegeclasses5   
...         ...              ...   
393106   393106   writerincanada   
393107   393107    ellimayradrep   
393108   393108  viniciusnikolod   
393109   393109      JamesEFinch   
393110   393110         nscrowba   
393111   393111       book_tribe   
393112   393112         jp_flyer   
393113   393113       ruby_wine_   
393114   393114      DebraRobbin   
393115   393115      StevenGuggs   
393116   393116      PeterFeaman   
393117   393117  Tucs0nMortgages   
393118   393118  tlacovaspravask   
393119   393119      King17Larry   
393120   393120         Rparisee   
393121   393121        Adam_Eire   
393122   393122   mikefreemanNFL   
393123   393123        tomcat159   
393124   393124     Zwoodbutcher   
393125   393125        EINITNews   
393126   393126   AlgerianPalest   
393127   393127    kingofponders   
393128   393128      KosPatricia   
393129   393129     TwittaChicca   
393130   393130   BuffyLibSlayer   
393131   393131       boaomega22   
393132   393132   April_Magazine   
393133   393133         Noofer55   
393134   393134           ZBezzt   
393135   393135         pewdrdad   

                                                     text        replyToSN  \
1         American Harem.. #MeToo https://t.co/HjExLJdGuF              NaN   
2       @johnconyersjr  @alfranken  why have you guys ...    johnconyersjr   
3       Watched Megan Kelly ask Joe Keery this A.M. if...              NaN   
4       Women have been talking about this crap the en...              NaN   
5       .@BetteMidler please speak to this sexual assa...              NaN   
6       We can't keep turning a blind eye and pretend ...              NaN   
7       Jay-Z is saying what I've been saying. DJT's j...              NaN   
8       Where in the world is @MattLauer Celebrate #MeToo              NaN   
9              @JoyAnnReid Keep it coming ladies!  #MeToo       JoyAnnReid   
10      @RepAdamSmith Workplace is one place, but what...     RepAdamSmith   
11      Is it just me or does the #MeToo <----icon; fr...              NaN   
12      Just  got scammed out of  $25.  Bought #TigerW...              NaN   
13      @RepKathleenRice @RepJayapal Calling out @RepJ...  RepKathleenRice   
14                   #BlackLivesMatter with #MeToo yup ok              NaN   
15      Why are not the men haters from #Metoo marchin...              NaN   
16      I was sexually harassed as a "young Intern" fo...              NaN   
17      So I have a question. This post was published ...              NaN   
18      Im pretty sure @DanRather and Brian Williams a...              NaN   
19      Aint trying to start nothing but wouldnt it be...              NaN   
20      How can @realDonaldTrump talk about anyone tha...              NaN   
21      Yes!! WHEN it happens to you, THEN you can dec...              NaN   
22      @CNN Read: "we must destroy the oppressive pat...  

In [27]:
uniqueUsers = uniqueUsers[['screenName']]
uniqueUsers.drop_duplicates(inplace=True)

In [28]:
uniqueUsers[uniqueUsers['screenName'].isna()]

Empty DataFrame
Columns: [screenName]
Index: []

In [29]:
df['screenName'].nunique() == len(uniqueUsers)

True

In [30]:
uniqueUsers

screenName
1             ahmediaTV
2        JesusPrepper74
3        DemerisePotvin
4          TheDawnStott
5        scottygirl2014
6          ForEverBrenn
7        silveriaalison
8              calrican
9        traugott_sarah
10      SchifanoRaelene
11          BrunusCutis
12           RDonSteele
13         _standeliver
14             dbehan79
15           european_4
16      FrancescaBiller
17       emilyjoypoetry
18             frozenjo
19             num1_fan
20          DougsMom204
21             page_lie
22      VirginiusPrimus
23           1mimi4ever
24          justshocked
25        ProphetPhella
26       womanontheleft
27            JessLivMo
28              JC4ever
30      collegeclasses5
31            BRellator
...                 ...
393062    davidwood1121
393063  lordioushulaio1
393065         cacisa2j
393068    AVagabondSoul
393071   MermaidsMatter
393073   MichelPLeblanc
393074        baxter375
393075  HendershotWendy
393076        Titiduvar
393077  realSilverFoxXL
393080  metsubokumatsur
393082      Ra_Koellner
393091    SagarYogendra
393093    Maureen_Lapis
393095  laborarestorare
393097          mdowney
393105      mminthecity
393112         jp_flyer
393113       ruby_wine_
393114      DebraRobbin
393115      StevenGuggs
393117  Tucs0nMortgages
393119      King17Larry
393121        Adam_Eire
393122   mikefreemanNFL
393123        tomcat159
393126   AlgerianPalest
393127    kingofponders
393128      KosPatricia
393134           ZBezzt

[222311 rows x 1 columns]

In [31]:
uniqueUsers.to_csv('Data/users.csv', index=False)

## Hashtags

In [32]:
hashtag = df[['tweetId','screenName', 'text']]

In [33]:
hashtags_extracted = hashtag['text'].str.extractall('(?P<hashtag>#\w+)')
hashtags_extracted.head(10)

hashtag
   match             
1  0           #MeToo
2  0           #MeToo
4  0           #metoo
5  0           #MeToo
6  0           #metoo
7  0           #metoo
8  0           #MeToo
9  0           #MeToo
11 0           #MeToo
12 0      #TigerWoods

Again, I need to reset the second index

In [34]:
hashtags_extracted = hashtags_extracted.reset_index(level=1)
hashtags_extracted.head()

match hashtag
1      0  #MeToo
2      0  #MeToo
4      0  #metoo
5      0  #MeToo
6      0  #metoo

Great. Now I just need to join the tweetId and merge back to the dataframe 'hashtag'.

In [35]:
hashtags_extracted = hashtags_extracted.join(hashtag['tweetId'])
hashtags_extracted

match            hashtag  tweetId
1           0             #MeToo        1
2           0             #MeToo        2
4           0             #metoo        4
5           0             #MeToo        5
6           0             #metoo        6
7           0             #metoo        7
8           0             #MeToo        8
9           0             #MeToo        9
11          0             #MeToo       11
12          0        #TigerWoods       12
14          0  #BlackLivesMatter       14
14          1             #MeToo       14
15          0             #Metoo       15
15          1    #UnsealTheDeals       15
19          0             #MeToo       19
21          0  #SupportSurvivors       21
22          0             #MeToo       22
23          0             #MeToo       23
24          0         #MattLauer       24
25          0       #SexualAbuse       25
26          0         #MattLauer       26
26          1           #NoMoore       26
26          2             #MeToo       26
26          3       #WomenResist       26
26          4               #RWU       26
27          0             #Metoo       27
28          0             #AbLeg       28
29          0             #metoo       29
29          1    #UnsealTheDeals       29
30          0             #metoo       30
...       ...                ...      ...
393108      0             #MeToo   393108
393110      0             #MeToo   393110
393111      0             #metoo   393111
393112      0             #metoo   393112
393113      0             #metoo   393113
393114      0             #MeToo   393114
393115      0             #MeToo   393115
393116      0             #MeToo   393116
393117      0             #MeToo   393117
393118      0             #MeToo   393118
393119      0             #MeToo   393119
393120      0             #metoo   393120
393121      0             #MeToo   393121
393121      1           #JAXvsSF   393121
393121      2           #Jaguars   393121
393122      0             #MeToo   393122
393123      0             #MeToo   393123
393124      0             #MeToo   393124
393125      0             #MeToo   393125
393126      0             #MeToo   393126
393127      0             #MeToo   393127
393128      0             #MeToo   393128
393129      0             #MeToo   393129
393130      0             #MeToo   393130
393131      0             #MeToo   393131
393132      0             #MeToo   393132
393133      0             #MeToo   393133
393134      0           #Consent   393134
393134      1             #MeToo   393134
393135      0             #MeToo   393135

[535838 rows x 3 columns]

In [36]:
hashtags_extracted['hashtag'] = hashtags_extracted['hashtag'].str.replace(r'#metoo', '#MeToo')
hashtags_extracted['hashtag'] = hashtags_extracted['hashtag'].str.replace(r'#Metoo', '#MeToo')
hashtags_extracted['hashtag'] = hashtags_extracted['hashtag'].str.replace(r'#METOO', '#MeToo')

In [37]:
hashtags_extracted = hashtags_extracted[['tweetId', 'hashtag']]
hashtags_extracted

tweetId            hashtag
1             1             #MeToo
2             2             #MeToo
4             4             #MeToo
5             5             #MeToo
6             6             #MeToo
7             7             #MeToo
8             8             #MeToo
9             9             #MeToo
11           11             #MeToo
12           12        #TigerWoods
14           14  #BlackLivesMatter
14           14             #MeToo
15           15             #MeToo
15           15    #UnsealTheDeals
19           19             #MeToo
21           21  #SupportSurvivors
22           22             #MeToo
23           23             #MeToo
24           24         #MattLauer
25           25       #SexualAbuse
26           26         #MattLauer
26           26           #NoMoore
26           26             #MeToo
26           26       #WomenResist
26           26               #RWU
27           27             #MeToo
28           28             #AbLeg
29           29             #MeToo
29           29    #UnsealTheDeals
30           30             #MeToo
...         ...                ...
393108   393108             #MeToo
393110   393110             #MeToo
393111   393111             #MeToo
393112   393112             #MeToo
393113   393113             #MeToo
393114   393114             #MeToo
393115   393115             #MeToo
393116   393116             #MeToo
393117   393117             #MeToo
393118   393118             #MeToo
393119   393119             #MeToo
393120   393120             #MeToo
393121   393121             #MeToo
393121   393121           #JAXvsSF
393121   393121           #Jaguars
393122   393122             #MeToo
393123   393123             #MeToo
393124   393124             #MeToo
393125   393125             #MeToo
393126   393126             #MeToo
393127   393127             #MeToo
393128   393128             #MeToo
393129   393129             #MeToo
393130   393130             #MeToo
393131   393131             #MeToo
393132   393132             #MeToo
393133   393133             #MeToo
393134   393134           #Consent
393134   393134             #MeToo
393135   393135             #MeToo

[535838 rows x 2 columns]

In [38]:
hashtag = pd.merge(hashtag, hashtags_extracted, how='right', on='tweetId')
hashtag

tweetId       screenName  \
0             1        ahmediaTV   
1             2   JesusPrepper74   
2             4     TheDawnStott   
3             5   scottygirl2014   
4             6     ForEverBrenn   
5             7   silveriaalison   
6             8         calrican   
7             9   traugott_sarah   
8            11      BrunusCutis   
9            12       RDonSteele   
10           14         dbehan79   
11           14         dbehan79   
12           15       european_4   
13           15       european_4   
14           19         num1_fan   
15           21         page_lie   
16           22  VirginiusPrimus   
17           23       1mimi4ever   
18           24      justshocked   
19           25    ProphetPhella   
20           26   womanontheleft   
21           26   womanontheleft   
22           26   womanontheleft   
23           26   womanontheleft   
24           26   womanontheleft   
25           27        JessLivMo   
26           28          JC4ever   
27           29       european_4   
28           29       european_4   
29           30  collegeclasses5   
...         ...              ...   
535808   393108  viniciusnikolod   
535809   393110         nscrowba   
535810   393111       book_tribe   
535811   393112         jp_flyer   
535812   393113       ruby_wine_   
535813   393114      DebraRobbin   
535814   393115      StevenGuggs   
535815   393116      PeterFeaman   
535816   393117  Tucs0nMortgages   
535817   393118  tlacovaspravask   
535818   393119      King17Larry   
535819   393120         Rparisee   
535820   393121        Adam_Eire   
535821   393121        Adam_Eire   
535822   393121        Adam_Eire   
535823   393122   mikefreemanNFL   
535824   393123        tomcat159   
535825   393124     Zwoodbutcher   
535826   393125        EINITNews   
535827   393126   AlgerianPalest   
535828   393127    kingofponders   
535829   393128      KosPatricia   
535830   393129     TwittaChicca   
535831   393130   BuffyLibSlayer   
535832   393131       boaomega22   
535833   393132   April_Magazine   
535834   393133         Noofer55   
535835   393134           ZBezzt   
535836   393134           ZBezzt   
535837   393135         pewdrdad   

                                                     text            hashtag  
0         American Harem.. #MeToo https://t.co/HjExLJdGuF             #MeToo  
1       @johnconyersjr  @alfranken  why have you guys ...             #MeToo  
2       Women have been talking about this crap the en...             #MeToo  
3       .@BetteMidler please speak to this sexual assa...             #MeToo  
4       We can't keep turning a blind eye and pretend ...             #MeToo  
5       Jay-Z is saying what I've been saying. DJT's j...             #MeToo  
6       Where in the world is @MattLauer Celebrate #MeToo             #MeToo  
7              @JoyAnnReid Keep it coming ladies!  #MeToo             #MeToo  
8       Is it just me or does the #MeToo <----icon; fr...             #MeToo  
9       Just  got scammed out of  $25.  Bought #TigerW...        #TigerWoods  
10                   #BlackLivesMatter with #MeToo yup ok  #BlackLivesMatter  
11                   #BlackLivesMatter with #MeToo yup ok             #MeToo  
12      Why are not the men haters from #Metoo marchin...             #MeToo  
13      Why are not the men haters from #Metoo marchin...    #UnsealTheDeals  
14      Aint trying to start nothing but wouldnt it be...             #MeToo  
15      Yes!! WHEN it happens to you, THEN you can dec...  #SupportSurvivors  
16      @CNN Read: "we must destroy the oppressive pat...             #MeToo  
17      @SaveUSA1776 Until I learned he did, I don't l...             #MeToo  
18      men all over this country are seeking ways to ...         #MattLauer  
19      @RealDonaldTrump How Much Did @JakeTapper thet...       #SexualAbuse  
20      Geraldo Rivera says "news is a flirty business...         #MattLauer  
21      Geraldo Rivera says "news is 

In [39]:
hashtag.drop('text',1,inplace=True)

In [40]:
hashtag.to_csv('Data/hashtags.csv', index=False)

# Association

Here I'm going to create a DataFrame that lists tweets that are:<br>
{category: condition}

Original:
- retweet: isRetweet is True
- reply: 'replyToSN' is not NaN
- mention: contains '@'

Updated:
- retweet
 - 'isRetweet' == True
- reply
 - 'replyToSN' is not NaN
 - 'text' starts with '@'
- mention
 - 'isRetweet' == False
 - 'replyToSN' is NaN
 - 'text' contains but does not start with '@'
- self
 - 'isRetweet' == False
 - 'replyToSN' is NaN
 - 'text' does not contain '@'

in all possible 1-to-1 combinations

In [41]:
# df = pd.read_sql('SELECT tweetId, screenName, text from tweets', con)
df = pd.read_csv('Data/tweets.csv')
df = df[['tweetId', 'screenName', 'text', 'replyToSN', 'isRetweet']]

In [42]:
len(df)
print('reply: "replyToSN" is not NaN')
np.logical_not(df['replyToSN'].isna()).value_counts()
print('isRetweet')
df['isRetweet'].value_counts()
print('contains "RT"')
df['text'].str.contains('RT').value_counts()
print('mention: contains "@"')
df['text'].str.contains('@').value_counts()

393135

reply: "replyToSN" is not NaN


False    343419
True      49716
Name: replyToSN, dtype: int64

isRetweet


True     224719
False    168416
Name: isRetweet, dtype: int64

contains "RT"


True     227089
False    166046
Name: text, dtype: int64

mention: contains "@"


True     297378
False     95757
Name: text, dtype: int64

of 393135 tweets...
- 49716 (12.6%) were created as a response to another user/tweet
- 224719 (57.2%) were labaled as True for 'isRetweet'
- 227089 (57.8%) contained 'RT'
- 297378 (75.6%) contained '@', most/many of which are likely tagging another user

Now, I need to determine how I will classify retweets:
- contains 'RT' followed by a username? or
- 'isRetweet' labeled as True?

Let's look at the 'text' columns deeper

In [43]:
len(df[df['isRetweet'] == True])
df[df['isRetweet'] == True]['text'].str.contains('RT').value_counts()

224719

True     224702
False        17
Name: text, dtype: int64

Of the 224719 tweets where 'isRetweet' is True, all but 17 of them contain 'RT'<br>
Let's look tweets where 'isRetweet' is True, and 'text' does not contain 'RT'

In [44]:
isRetweet = df[df['isRetweet'] == True]
isRetweet[np.logical_not(isRetweet['text'].str.contains('RT'))]

tweetId       screenName  \
248421   248422    Noone82270905   
265635   265636    Noone82270905   
282493   282494    CharleenRyan4   
380535   380536     Femen_France   
388852   388853   sapiens_no_2_1   
389602   389603         PjjPjoje   
389673   389674  sarahconstantin   
389686   389687     isikiniwapo1   
389732   389733        Me_Too_Us   
389777   389778         Max2Jets   
389779   389780    lautreamont13   
389998   389999         avrollot   
390941   390942       chloeArnxB   
390944   390945      alinspirit3   
390968   390969        Schadock4   
390970   390971  alliance_femmes   
390973   390974     Femen_France   

                                                     text replyToSN  isRetweet  
248421  @Noone82270905's account is temporarily unavai...       NaN       True  
265635  @Noone82270905's account is temporarily unavai...       NaN       True  
282493  @CharleenRyan4's account is temporarily unavai...       NaN       True  
380535  This Tweet from @Femen_France is temporarily u...       NaN       True  
388852  This Tweet from @sapiens_no_2_1 has been withh...       NaN       True  
389602  This Tweet from @PjjPjoje has been withheld in...       NaN       True  
389673  This Tweet from @sarahconstantin has been with...       NaN       True  
389686  This Tweet from @isikiniwapo1 has been withhel...       NaN       True  
389732  This Tweet from @Me_Too_Us has been withheld i...       NaN       True  
389777  This Tweet from @Max2Jets has been withheld in...       NaN       True  
389779  This Tweet from @lautreamont13 has been withhe...       NaN       True  
389998  This Tweet from @avrollot has been withheld in...       NaN       True  
390941  This Tweet from @chloeArnxB has been withheld ...       NaN       True  
390944  This Tweet from @alinspirit3 has been withheld...       NaN       True  
390968  This Tweet from @Schadock4 has been withheld i...       NaN       True  
390970  This Tweet from @alliance_femmes has been with...       NaN       True  
390973  This Tweet from @Femen_France is temporarily u...       NaN       True

Interesting, all of them seem to be suspended or tweets have been taken down.<br>
Let's drop these.

In [45]:
# tweetIds that will be flagged
flag = isRetweet[np.logical_not(isRetweet['text'].str.contains('RT'))]['tweetId']
flag

248421    248422
265635    265636
282493    282494
380535    380536
388852    388853
389602    389603
389673    389674
389686    389687
389732    389733
389777    389778
389779    389780
389998    389999
390941    390942
390944    390945
390968    390969
390970    390971
390973    390974
Name: tweetId, dtype: int64

In [46]:
df = pd.read_csv('Data/tweets.csv', encoding='utf-8')

In [47]:
# drop the tweets
len(flag)
len(df)
df.drop(df[df['tweetId'].isin(flag)].index, inplace=True)
len(df)

17

393135

393118

In [48]:
df.to_csv('Data/tweets.csv', index=False, encoding='utf-8')

Now, 'isRetweet' == True will be an indicator for Retweets


## Reply

In [49]:
df = pd.read_csv('Data/tweets.csv', encoding='utf-8')

In [50]:
reply = df[(df['replyToSN'].isnull() == False) & (df['text'].str.startswith('@') == True)][['tweetId','screenName','replyToSN']]
reply

tweetId       screenName        replyToSN
1             2   JesusPrepper74    johnconyersjr
8             9   traugott_sarah       JoyAnnReid
9            10  SchifanoRaelene     RepAdamSmith
12           13     _standeliver  RepKathleenRice
21           22  VirginiusPrimus              CNN
22           23       1mimi4ever      SaveUSA1776
24           25    ProphetPhella  realDonaldTrump
31           32    genesis427427       btweet2all
35           36          nvygrl1    GeraldoRivera
38           39      roadgearsun       samaralynn
44           45        RibaSusan       DannyZuker
54           55    KarenCallesoe    Alyssa_Milano
55           56        TamDawg79  realDonaldTrump
56           57        IE_ANTIFA     Soros_Antifa
57           58           stcks4    GeraldoRivera
64           65    adelesammarco    adelesammarco
67           68       shnikies78         SebGorka
68           69            ctlss          heierup
73           74     icarusfactor              CNN
75           76        CamRooMom      CoachTDavis
79           80    tealraspberry   shortyblueyes5
80           81    AnitaSurridge    GeraldoRivera
87           88      blaiserbeam  Heavens_Angel26
88           89       savvysuzee       Joyannah73
93           94    JerusalemFury       jaketapper
96           97      AriaaJaeger      BetteMidler
99          100  LostInTheMovies        Unitynow8
101         102              kim    GeraldoRivera
102         103   disqualify_gop     Anti_DJTrump
103         104        slickleg1    GeraldoRivera
...         ...              ...              ...
392830   392848      Auroraknite       babzylonia
392860   392878  RobbysRamblings      Auroraknite
392868   392886  RobbysRamblings      Auroraknite
392882   392900         cedd6321          nytimes
392890   392908    scarlettstuff   writerincanada
392912   392930      morrowchris   Misstabstevens
392926   392944  KekistanAntifa1        cenkuygur
392929   392947       babzylonia      Auroraknite
392931   392949        accio_fer          debsaok
392939   392957         cedd6321          nytimes
392944   392962   JohnathanLaird  Cleverestcookie
392949   392967           Eli414      BradMossEsq
392950   392968      leecylou701      rosemcgowan
392951   392969        brokeposi        brokeposi
392957   392975    DystopiaSoaks     Steve_Sailer
392960   392978    Big_Gay_Randy     joyellen1962
392964   392982      clearview56    4lisaguerrero
392988   393006     tmviggnocchi   kurteichenwald
393033   393051      MeggyLepepe  BonnieEisenberg
393035   393053  bikemamadelphia  HereComesTreb1e
393046   393064  Coloredeyesmark           remoca
393047   393065         cacisa2j         N_Fatale
393051   393069      Auroraknite       babzylonia
393059   393077  realSilverFoxXL      LauraLoomer
393071   393089      Kek_says_FU     PetiteNicoco
393076   393094         ADmomof3      rosemcgowan
393077   393095  laborarestorare          Twitter
393085   393103           SFardd     PetiteNicoco
393094   393112         jp_flyer      VanillaLady
393103   393121        Adam_Eire          Jaguars

[47014 rows x 3 columns]

In [51]:
reply['associationType'] = 'reply'
reply = reply[['tweetId','screenName','associationType','replyToSN']]
reply.columns = ['tweetId','screenName', 'associationType', 'keyword']
reply

tweetId       screenName associationType          keyword
1             2   JesusPrepper74           reply    johnconyersjr
8             9   traugott_sarah           reply       JoyAnnReid
9            10  SchifanoRaelene           reply     RepAdamSmith
12           13     _standeliver           reply  RepKathleenRice
21           22  VirginiusPrimus           reply              CNN
22           23       1mimi4ever           reply      SaveUSA1776
24           25    ProphetPhella           reply  realDonaldTrump
31           32    genesis427427           reply       btweet2all
35           36          nvygrl1           reply    GeraldoRivera
38           39      roadgearsun           reply       samaralynn
44           45        RibaSusan           reply       DannyZuker
54           55    KarenCallesoe           reply    Alyssa_Milano
55           56        TamDawg79           reply  realDonaldTrump
56           57        IE_ANTIFA           reply     Soros_Antifa
57           58           stcks4           reply    GeraldoRivera
64           65    adelesammarco           reply    adelesammarco
67           68       shnikies78           reply         SebGorka
68           69            ctlss           reply          heierup
73           74     icarusfactor           reply              CNN
75           76        CamRooMom           reply      CoachTDavis
79           80    tealraspberry           reply   shortyblueyes5
80           81    AnitaSurridge           reply    GeraldoRivera
87           88      blaiserbeam           reply  Heavens_Angel26
88           89       savvysuzee           reply       Joyannah73
93           94    JerusalemFury           reply       jaketapper
96           97      AriaaJaeger           reply      BetteMidler
99          100  LostInTheMovies           reply        Unitynow8
101         102              kim           reply    GeraldoRivera
102         103   disqualify_gop           reply     Anti_DJTrump
103         104        slickleg1           reply    GeraldoRivera
...         ...              ...             ...              ...
392830   392848      Auroraknite           reply       babzylonia
392860   392878  RobbysRamblings           reply      Auroraknite
392868   392886  RobbysRamblings           reply      Auroraknite
392882   392900         cedd6321           reply          nytimes
392890   392908    scarlettstuff           reply   writerincanada
392912   392930      morrowchris           reply   Misstabstevens
392926   392944  KekistanAntifa1           reply        cenkuygur
392929   392947       babzylonia           reply      Auroraknite
392931   392949        accio_fer           reply          debsaok
392939   392957         cedd6321           reply          nytimes
392944   392962   JohnathanLaird           reply  Cleverestcookie
392949   392967           Eli414           reply      BradMossEsq
392950   392968      leecylou701           reply      rosemcgowan
392951   392969        brokeposi           reply        brokeposi
392957   392975    DystopiaSoaks           reply     Steve_Sailer
392960   392978    Big_Gay_Randy           reply     joyellen1962
392964   392982      clearview56           reply    4lisaguerrero
392988   393006     tmviggnocchi           reply   kurteichenwald
393033   393051      MeggyLepepe           reply  BonnieEisenberg
393035   393053  bikemamadelphia           reply  HereComesTreb1e
393046   393064  Coloredeyesmark           reply           remoca
393047   393065         cacisa2j           reply         N_Fatale
393051   393069      Auroraknite           reply       babzylonia
393059   393077  realSilverFoxXL           reply      LauraLoomer
393071   393089      Kek_says_FU           reply     PetiteNicoco
393076   393094         ADmomof3           reply      rosemcgowan
393077   393095  laborarestorare           reply          Twitter
393085   393103           SFardd           reply     PetiteNicoco
393094   393112         jp_flyer           reply

## Retweet

In [52]:
df = pd.read_csv('Data/tweets.csv')

In [53]:
df

tweetId       screenName  \
0             1        ahmediaTV   
1             2   JesusPrepper74   
2             3   DemerisePotvin   
3             4     TheDawnStott   
4             5   scottygirl2014   
5             6     ForEverBrenn   
6             7   silveriaalison   
7             8         calrican   
8             9   traugott_sarah   
9            10  SchifanoRaelene   
10           11      BrunusCutis   
11           12       RDonSteele   
12           13     _standeliver   
13           14         dbehan79   
14           15       european_4   
15           16  FrancescaBiller   
16           17   emilyjoypoetry   
17           18         frozenjo   
18           19         num1_fan   
19           20      DougsMom204   
20           21         page_lie   
21           22  VirginiusPrimus   
22           23       1mimi4ever   
23           24      justshocked   
24           25    ProphetPhella   
25           26   womanontheleft   
26           27        JessLivMo   
27           28          JC4ever   
28           29       european_4   
29           30  collegeclasses5   
...         ...              ...   
393088   393106   writerincanada   
393089   393107    ellimayradrep   
393090   393108  viniciusnikolod   
393091   393109      JamesEFinch   
393092   393110         nscrowba   
393093   393111       book_tribe   
393094   393112         jp_flyer   
393095   393113       ruby_wine_   
393096   393114      DebraRobbin   
393097   393115      StevenGuggs   
393098   393116      PeterFeaman   
393099   393117  Tucs0nMortgages   
393100   393118  tlacovaspravask   
393101   393119      King17Larry   
393102   393120         Rparisee   
393103   393121        Adam_Eire   
393104   393122   mikefreemanNFL   
393105   393123        tomcat159   
393106   393124     Zwoodbutcher   
393107   393125        EINITNews   
393108   393126   AlgerianPalest   
393109   393127    kingofponders   
393110   393128      KosPatricia   
393111   393129     TwittaChicca   
393112   393130   BuffyLibSlayer   
393113   393131       boaomega22   
393114   393132   April_Magazine   
393115   393133         Noofer55   
393116   393134           ZBezzt   
393117   393135         pewdrdad   

                                                     text        replyToSN  \
0         American Harem.. #MeToo https://t.co/HjExLJdGuF              NaN   
1       @johnconyersjr  @alfranken  why have you guys ...    johnconyersjr   
2       Watched Megan Kelly ask Joe Keery this A.M. if...              NaN   
3       Women have been talking about this crap the en...              NaN   
4       .@BetteMidler please speak to this sexual assa...              NaN   
5       We can't keep turning a blind eye and pretend ...              NaN   
6       Jay-Z is saying what I've been saying. DJT's j...              NaN   
7       Where in the world is @MattLauer Celebrate #MeToo              NaN   
8              @JoyAnnReid Keep it coming ladies!  #MeToo       JoyAnnReid   
9       @RepAdamSmith Workplace is one place, but what...     RepAdamSmith   
10      Is it just me or does the #MeToo <----icon; fr...              NaN   
11      Just  got scammed out of  $25.  Bought #TigerW...              NaN   
12      @RepKathleenRice @RepJayapal Calling out @RepJ...  RepKathleenRice   
13                   #BlackLivesMatter with #MeToo yup ok              NaN   
14      Why are not the men haters from #Metoo marchin...              NaN   
15      I was sexually harassed as a "young Intern" fo...              NaN   
16      So I have a question. This post was published ...              NaN   
17      Im pretty sure @DanRather and Brian Williams a...              NaN   
18      Aint trying to start nothing but wouldnt it be...              NaN   
19      How can @realDonaldTrump talk about anyone tha...              NaN   
20      Yes!! WHEN it happens to you, THEN you can dec...              NaN   
21      @CNN Read: "we must destroy the oppressive pat...  

In [54]:
retweet = df[df['isRetweet'] == True][['tweetId','screenName', 'text']]
retweet

tweetId       screenName  \
4997       4998         wordsrox   
4998       4999    Objective_ish   
5000       5001       criynwa293   
5001       5002       krissymom2   
5003       5004        jestor810   
5004       5005         LisaD787   
5006       5007           GBan14   
5007       5008  MsHasNoPatience   
5009       5010       Perspectvz   
5010       5011  CarnivoraUrsida   
5012       5013          dktturn   
5014       5015         emmala91   
5015       5016  lnreadingaround   
5017       5018    CadenceDenton   
5020       5021        Lehigh389   
5021       5022      CDNArchives   
5024       5025  TheRightImageLV   
5027       5028         cmcc1975   
5030       5031      itchywitch2   
5031       5032      susendipity   
5032       5033     RuralLiberal   
5033       5034          echerio   
5037       5038  MalindaMichell1   
5040       5041          dw_hanz   
5041       5042  vargas_ypvargas   
5043       5044       ShazzLa_La   
5045       5046          KitCoco   
5046       5047     SianLouise34   
5048       5049       lewisroche   
5052       5053        NimrLaura   
...         ...              ...   
393074   393092         TIFF_NET   
393075   393093    Maureen_Lapis   
393078   393096       DeleHaynes   
393079   393097          mdowney   
393080   393098  CindyBo83683099   
393082   393100         apq11235   
393083   393101       Aschettino   
393084   393102   MonicaTaveras3   
393086   393104   SEBASTIANCAT75   
393087   393105      mminthecity   
393088   393106   writerincanada   
393089   393107    ellimayradrep   
393090   393108  viniciusnikolod   
393092   393110         nscrowba   
393096   393114      DebraRobbin   
393097   393115      StevenGuggs   
393099   393117  Tucs0nMortgages   
393100   393118  tlacovaspravask   
393101   393119      King17Larry   
393102   393120         Rparisee   
393104   393122   mikefreemanNFL   
393105   393123        tomcat159   
393106   393124     Zwoodbutcher   
393108   393126   AlgerianPalest   
393109   393127    kingofponders   
393110   393128      KosPatricia   
393111   393129     TwittaChicca   
393112   393130   BuffyLibSlayer   
393113   393131       boaomega22   
393116   393134           ZBezzt   

                                                     text  
4997    RT @NancyPelosi: Proud to stand with @RepSpeie...  
4998    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5000    RT @jonfavs: NEW POD: Legislative looting and ...  
5001    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5003    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5004    RT @earthma23: @davrosz I have a couple of ide...  
5006    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5007    RT @SarahSpain: Many have been asking when the...  
5009    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5010    RT @wesley_jordan: Thank you @BetteMidler!  Te...  
5012    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5014    RT @Newsweek: Hillary Clinton dodges question ...  
5015    RT @BoringMe2Death: #MeToo: How an 11-year-old...  
5017    RT @LyndiLamont: The Sad Phenomenon of #MeToo ...  
5020    RT @JenAshleyWright: Wrote about how to deal w...  
5021    RT @Marcodeplume: @AzfarRizvi @terrycrews I be...  
5024    RT @JamesJordy: FIRE HIS ASS  HE'S ALWAYS BEEN...  
5027    RT @MaureenShaw: Random thought: I bet it woul...  
5030    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5031    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5032    RT @IjeomaOluo: I wrote about my recent experi...  
5033    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5037    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5040    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5041    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5043    RT @IjeomaOluo: I wrote about my recent experi...  
5045    RT @NancyPelosi: Proud to stand with @RepSpeie...  
5046    RT @ThrupennyBit: Hot take on the way patriarc...  
5048    RT @NancyPelosi: Proud to s

In [55]:
# ensuring that row counts are the same
retweet['text'].str.startswith('RT @').value_counts()

True    224702
Name: text, dtype: int64

In [56]:
retweet['keyword'] = retweet['text'].str.extract(r'RT @(\w+)')

In [57]:
retweet.drop('text',1,inplace=True)
retweet['associationType'] = 'retweet'
retweet = retweet[['tweetId','screenName','associationType','keyword']]
retweet

tweetId       screenName associationType          keyword
4997       4998         wordsrox         retweet      NancyPelosi
4998       4999    Objective_ish         retweet      NancyPelosi
5000       5001       criynwa293         retweet          jonfavs
5001       5002       krissymom2         retweet      NancyPelosi
5003       5004        jestor810         retweet      NancyPelosi
5004       5005         LisaD787         retweet        earthma23
5006       5007           GBan14         retweet      NancyPelosi
5007       5008  MsHasNoPatience         retweet       SarahSpain
5009       5010       Perspectvz         retweet      NancyPelosi
5010       5011  CarnivoraUrsida         retweet    wesley_jordan
5012       5013          dktturn         retweet      NancyPelosi
5014       5015         emmala91         retweet         Newsweek
5015       5016  lnreadingaround         retweet   BoringMe2Death
5017       5018    CadenceDenton         retweet      LyndiLamont
5020       5021        Lehigh389         retweet  JenAshleyWright
5021       5022      CDNArchives         retweet     Marcodeplume
5024       5025  TheRightImageLV         retweet       JamesJordy
5027       5028         cmcc1975         retweet      MaureenShaw
5030       5031      itchywitch2         retweet      NancyPelosi
5031       5032      susendipity         retweet      NancyPelosi
5032       5033     RuralLiberal         retweet       IjeomaOluo
5033       5034          echerio         retweet      NancyPelosi
5037       5038  MalindaMichell1         retweet      NancyPelosi
5040       5041          dw_hanz         retweet      NancyPelosi
5041       5042  vargas_ypvargas         retweet      NancyPelosi
5043       5044       ShazzLa_La         retweet       IjeomaOluo
5045       5046          KitCoco         retweet      NancyPelosi
5046       5047     SianLouise34         retweet     ThrupennyBit
5048       5049       lewisroche         retweet      NancyPelosi
5052       5053        NimrLaura         retweet      NancyPelosi
...         ...              ...             ...              ...
393074   393092         TIFF_NET         retweet         TIFF_NET
393075   393093    Maureen_Lapis         retweet     EdgeofSports
393078   393096       DeleHaynes         retweet    OneMillionVjj
393079   393097          mdowney         retweet        Microsoft
393080   393098  CindyBo83683099         retweet         pewdrdad
393082   393100         apq11235         retweet  Suffragentleman
393083   393101       Aschettino         retweet       nhregister
393084   393102   MonicaTaveras3         retweet      LauraLoomer
393086   393104   SEBASTIANCAT75         retweet    ProudResister
393087   393105      mminthecity         retweet         MzCSmith
393088   393106   writerincanada         retweet        _JustGee_
393089   393107    ellimayradrep         retweet         pewdrdad
393090   393108  viniciusnikolod         retweet      LauraLoomer
393092   393110         nscrowba         retweet      SteveBannen
393096   393114      DebraRobbin         retweet  WithoutViolence
393097   393115      StevenGuggs         retweet        Microsoft
393099   393117  Tucs0nMortgages         retweet             raju
393100   393118  tlacovaspravask         retweet      SteveBannen
393101   393119      King17Larry         retweet      LauraLoomer
393102   393120         Rparisee         retweet   peaceandjoy101
393104   393122   mikefreemanNFL         retweet         MzCSmith
393105   393123        tomcat159         retweet      SteveBannen
393106   393124     Zwoodbutcher         retweet      NevadaJack2
393108   393126   AlgerianPalest         retweet   YousefMunayyer
393109   393127    kingofponders         retweet  Suffragentleman
393110   393128      KosPatricia         retweet      SteveBannen
393111   393129     TwittaChicca         retweet    TianaTheFirst
393112   393130   BuffyLibSlayer         retweet      LauraLoomer
393113   393131       boaomega22         retweet

## Mention

In [58]:
mention = df[['tweetId','screenName', 'text', 'isRetweet', 'replyToSN']]

In [59]:
mention = mention[mention['replyToSN'].isnull() & (mention['isRetweet'] == False)]
mention

tweetId       screenName  \
0             1        ahmediaTV   
2             3   DemerisePotvin   
3             4     TheDawnStott   
4             5   scottygirl2014   
5             6     ForEverBrenn   
6             7   silveriaalison   
7             8         calrican   
10           11      BrunusCutis   
11           12       RDonSteele   
13           14         dbehan79   
14           15       european_4   
15           16  FrancescaBiller   
16           17   emilyjoypoetry   
17           18         frozenjo   
18           19         num1_fan   
19           20      DougsMom204   
20           21         page_lie   
23           24      justshocked   
25           26   womanontheleft   
26           27        JessLivMo   
27           28          JC4ever   
28           29       european_4   
29           30  collegeclasses5   
30           31        BRellator   
32           33         page_lie   
33           34      J_R_Kestner   
36           37        GLucivero   
37           38       IndigoRave   
39           40        AliBerlow   
40           41      SWSupportLV   
...         ...              ...   
393010   393028   DougThorpe_com   
393012   393030  VictoriaHagstr2   
393017   393035  phillygodfather   
393018   393036           TheCut   
393020   393038     moosecustoms   
393022   393040         mjpthol1   
393023   393041    closethegapCA   
393024   393042    Ruthie_Murray   
393026   393044        HeloJapes   
393028   393046     KarmicAction   
393030   393048       MazenMahdi   
393036   393054          Bode834   
393041   393059    onejimharris_   
393044   393062    davidwood1121   
393045   393063  lordioushulaio1   
393052   393070      Elisheva_CA   
393053   393071   MermaidsMatter   
393054   393072      MeggyLepepe   
393056   393074        baxter375   
393062   393080  metsubokumatsur   
393070   393088       CDMitchell   
393081   393099         TIFF_NET   
393091   393109      JamesEFinch   
393093   393111       book_tribe   
393095   393113       ruby_wine_   
393098   393116      PeterFeaman   
393107   393125        EINITNews   
393114   393132   April_Magazine   
393115   393133         Noofer55   
393117   393135         pewdrdad   

                                                     text  isRetweet replyToSN  
0         American Harem.. #MeToo https://t.co/HjExLJdGuF      False       NaN  
2       Watched Megan Kelly ask Joe Keery this A.M. if...      False       NaN  
3       Women have been talking about this crap the en...      False       NaN  
4       .@BetteMidler please speak to this sexual assa...      False       NaN  
5       We can't keep turning a blind eye and pretend ...      False       NaN  
6       Jay-Z is saying what I've been saying. DJT's j...      False       NaN  
7       Where in the world is @MattLauer Celebrate #MeToo      False       NaN  
10      Is it just me or does the #MeToo <----icon; fr...      False       NaN  
11      Just  got scammed out of  $25.  Bought #TigerW...      False       NaN  
13                   #BlackLivesMatter with #MeToo yup ok      False       NaN  
14      Why are not the men haters from #Metoo marchin...      False       NaN  
15      I was sexually harassed as a "young Intern" fo...      False       NaN  
16      So I have a question. This post was published ...      False       NaN  
17      Im pretty sure @DanRather and Brian Williams a...      False       NaN  
18      Aint trying to start nothing but wouldnt it be...      False       NaN  
19      How can @realDonaldTrump talk about anyone tha...      False       NaN  
20      Yes!! WHEN it happens to you, THEN you can dec...      False       NaN  
23      men all over this country are seeking ways to ...      False       NaN  
25      Geraldo Rivera says "news is a flirty business...      False       NaN  
26      Political men: it is only a matter of time. #M...      False       NaN  
27      How do you reconcile your love of someone if t...      False      

In [60]:
mention = mention[np.logical_not(mention['text'].str.startswith('@')) & mention['text'].str.contains('@')]
mention

tweetId       screenName  \
4             5   scottygirl2014   
7             8         calrican   
16           17   emilyjoypoetry   
17           18         frozenjo   
19           20      DougsMom204   
29           30  collegeclasses5   
32           33         page_lie   
40           41      SWSupportLV   
46           47        BJFrezell   
52           53  jicReneeMerling   
60           61    JerusalemFury   
61           62    downrightdpad   
72           73       wendy08724   
83           84        emergingW   
85           86    BasedAlcatraz   
91           92     L2MyDaughter   
115         116      ExMilSpouse   
117         118     kellyswalden   
121         122        xenakixit   
127         128  Soumitradas4Das   
129         130         hannsimp   
157         158    DavidMcClain7   
164         165        kimcooper   
166         167        mazzou467   
171         172     aplusdoubleJ   
175         176  shannyncaldwell   
185         186        keftiugal   
188         189     MissShuganah   
192         193    darkhorse0102   
201         202       liahalonso   
...         ...              ...   
392671   392689         GemX29SC   
392704   392722          cavana3   
392707   392725    realguzzybear   
392723   392741             Kedz   
392768   392786     Farmer12Jane   
392769   392787  SantanaConsulta   
392770   392788     YoBuyThisNow   
392771   392789    ArtieSmartie1   
392772   392790  AmeliaImpulsive   
392773   392791  angie_santana20   
392784   392802     mvrhodes2000   
392801   392819    Queeenpenguin   
392844   392862      SWEngLeader   
392849   392867      MarinaGipps   
392856   392874          tredf69   
392884   392902  Heyitsablackguy   
392892   392910           ZivaBF   
392923   392941          rebel19   
392933   392951           JUNP_N   
392945   392963   DrunkenStupor1   
392946   392964          LPOYSOR   
392958   392976      roriIZfunny   
392974   392992     valoriecurry   
392993   393011  Carolyns_RVLife   
393020   393038     moosecustoms   
393022   393040         mjpthol1   
393023   393041    closethegapCA   
393024   393042    Ruthie_Murray   
393030   393048       MazenMahdi   
393041   393059    onejimharris_   

                                                     text  isRetweet replyToSN  
4       .@BetteMidler please speak to this sexual assa...      False       NaN  
7       Where in the world is @MattLauer Celebrate #MeToo      False       NaN  
16      So I have a question. This post was published ...      False       NaN  
17      Im pretty sure @DanRather and Brian Williams a...      False       NaN  
19      How can @realDonaldTrump talk about anyone tha...      False       NaN  
29      Kathleen Kane: The Rise and Fall | Philadelphi...      False       NaN  
32      And @headhntr freaking CONFESSED online last w...      False       NaN  
40      Sex Workers Deserve A Space To Voice #MeToo by...      False       NaN  
46      Thinking of @AnnCurry and the unpleasantness M...      False       NaN  
52      Yet #fakemedia & #Hollywood wants to use #Smok...      False       NaN  
60      Given the sexual harassment pandemic, I have t...      False       NaN  
61      If #MeToo wins @TIMEs Person of the Year, I th...      False       NaN  
72      Anyone else think maybe the @TIME person of th...      False       NaN  
83      At @emergingW we know women have been coming t...      False       NaN  
85      A sexual predator from @cnn gets fired. Anothe...      False       NaN  
91      So much for #MeToo https://t.co/M7w5H0geg7 via...      False       NaN  
115     WHEN is someone going to report on the sexual ...      False       NaN  
117     https://t.co/mwFrSLU8Nv SGIAMW: #MeToo @IamNan...      False       NaN  
121     <~~up on soapbox   Thank you @rosemcgowan for ...      False       NaN  
127     With #MeToo campaign fed firings galore, would...      False       NaN  
129     I was sexually harassed/touched at @WeAreTouro...      False      

In [61]:
mention['text'] = mention['text'].str.replace(r'(RT @\w+)', '')

In [62]:
mention['text'].str.contains('RT @').value_counts()

False    25255
True        12
Name: text, dtype: int64

In [63]:
# 12 of RT's couldn't be removed
mention[mention['text'].str.contains('RT @')]

tweetId     screenName  \
3116       3117  realityshowes   
7881       7882  realityshowes   
18180     18181  realityshowes   
25592     25593  realityshowes   
38617     38618  realityshowes   
52738     52739  realityshowes   
54254     54255  realityshowes   
112149   112150  realityshowes   
118825   118826     YESWECAN53   
118826   118827  whyfeedthem53   
118827   118828     NOLIMITS53   
321074   321078       shriparv   

                                                     text  isRetweet replyToSN  
3116    RT @ destiario: Typing in dictatorship #Venezu...      False       NaN  
7881    RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False       NaN  
18180   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False       NaN  
25592   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False       NaN  
38617   RT @ destiario: ‰Õü‰Õü‰_´Typing in dictatorshi...      False       NaN  
52738   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False       NaN  
54254   RT @ destiario: #Cine Dustin Hoffman Spars Wit...      False       NaN  
112149  RT @ destiario: ‚í∏‚í∏‚û•Typing in dictatorshi...      False       NaN  
118825  RT @ "#MT @funder The 16 women who accused Tru...      False       NaN  
118826  RT @ "#MT @funder The 16 women who accused Tru...      False       NaN  
118827  RT @ "#MT @funder The 16 women who accused Tru...      False       NaN  
321074  RT @ ( TarekFatah ) -  EXCLUSIVE ‚Äì Linda Sar...      False       NaN

In [64]:
mention['text2'] = mention['text'].str.replace(r'(RT @ \w+)', '')
mention[mention['text'].str.contains('RT @')]

tweetId     screenName  \
3116       3117  realityshowes   
7881       7882  realityshowes   
18180     18181  realityshowes   
25592     25593  realityshowes   
38617     38618  realityshowes   
52738     52739  realityshowes   
54254     54255  realityshowes   
112149   112150  realityshowes   
118825   118826     YESWECAN53   
118826   118827  whyfeedthem53   
118827   118828     NOLIMITS53   
321074   321078       shriparv   

                                                     text  isRetweet  \
3116    RT @ destiario: Typing in dictatorship #Venezu...      False   
7881    RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False   
18180   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False   
25592   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False   
38617   RT @ destiario: ‰Õü‰Õü‰_´Typing in dictatorshi...      False   
52738   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False   
54254   RT @ destiario: #Cine Dustin Hoffman Spars Wit...      False   
112149  RT @ destiario: ‚í∏‚í∏‚û•Typing in dictatorshi...      False   
118825  RT @ "#MT @funder The 16 women who accused Tru...      False   
118826  RT @ "#MT @funder The 16 women who accused Tru...      False   
118827  RT @ "#MT @funder The 16 women who accused Tru...      False   
321074  RT @ ( TarekFatah ) -  EXCLUSIVE ‚Äì Linda Sar...      False   

       replyToSN                                              text2  
3116         NaN  : Typing in dictatorship #Venezuela 2017  http...  
7881         NaN  : â’¸â’¸â_¥Typing in dictatorship #Venezuela 2...  
18180        NaN  : â’¸â’¸â_¥Typing in dictatorship #Venezuela 2...  
25592        NaN  : â’¸â’¸â_¥Typing in dictatorship #Venezuela 2...  
38617        NaN  : ‰Õü‰Õü‰_´Typing in dictatorship #Venezuela 2...  
52738        NaN  : â’¸â’¸â_¥Typing in dictatorship #Venezuela 2...  
54254        NaN  : #Cine Dustin Hoffman Spars With John Oliver ...  
112149       NaN  : ‚í∏‚í∏‚û•Typing in dictatorship #Venezuela 2...  
118825       NaN  RT @ "#MT @funder The 16 women who accused Tru...  
118826       NaN  RT @ "#MT @funder The 16 women who accused Tru...  
118827       NaN  RT @ "#MT @funder The 16 women who accused Tru...  
321074       NaN  RT @ ( TarekFatah ) -  EXCLUSIVE ‚Äì Linda Sar...

In [65]:
mention[mention['text'].str.contains('RT @')]['text2'].values

array([': Typing in dictatorship #Venezuela 2017  https://t.co/UyIWOlbtX0 #USA #KevinSpacey #Oscars #MeToo',
       ': â’¸â’¸â_¥Typing in dictatorship #Venezuela 2017 â˜› https://t.co/dvPuZdtnlB #USA #KevinSpacey #Oscars #MeToo',
       ': â’¸â’¸â_¥Typing in dictatorship #Venezuela 2017 â˜› https://t.co/dvPuZdtnlB #USA #KevinSpacey #Oscars #MeToo',
       ': â’¸â’¸â_¥Typing in dictatorship #Venezuela 2017 â˜› https://t.co/dvPuZdtnlB #USA #KevinSpacey #Oscars #MeToo',
       ': ‰Õü‰Õü‰_´Typing in dictatorship #Venezuela 2017 ‰÷_ https://t.co/dvPuZdtnlB #USA #KevinSpacey #Oscars #MeToo',
       ': â’¸â’¸â_¥Typing in dictatorship #Venezuela 2017 â˜› https://t.co/dvPuZdtnlB #USA #KevinSpacey #Oscars #MeToo',
       ': #Cine Dustin Hoffman Spars With John Oliver Over Harassment Claims: â€œYouâ€™ve Put Me On Display Hereâ€ùâ€_ https://t.co/pQmEF3JWG4',
       ': ‚í∏‚í∏‚û•Typing in dictatorship #Venezuela 2017 ‚òõ https://t.co/dvPuZdtnlB #USA #KevinSpacey #Oscars #MeToo',
       'RT @ "#MT @f

In [66]:
# I'll just remove "RT @ ( TarekFatah )" and "RT @ "#MT @funder" manually
mention['text2'] = mention['text2'].str.replace(r'RT @ \( TarekFatah \)', '')
mention['text2'] = mention['text2'].str.replace(r'RT @ \"#MT @funder', '')
mention[mention['text'].str.contains('RT @')]

tweetId     screenName  \
3116       3117  realityshowes   
7881       7882  realityshowes   
18180     18181  realityshowes   
25592     25593  realityshowes   
38617     38618  realityshowes   
52738     52739  realityshowes   
54254     54255  realityshowes   
112149   112150  realityshowes   
118825   118826     YESWECAN53   
118826   118827  whyfeedthem53   
118827   118828     NOLIMITS53   
321074   321078       shriparv   

                                                     text  isRetweet  \
3116    RT @ destiario: Typing in dictatorship #Venezu...      False   
7881    RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False   
18180   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False   
25592   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False   
38617   RT @ destiario: ‰Õü‰Õü‰_´Typing in dictatorshi...      False   
52738   RT @ destiario: â’¸â’¸â_¥Typing in dictatorshi...      False   
54254   RT @ destiario: #Cine Dustin Hoffman Spars Wit...      False   
112149  RT @ destiario: ‚í∏‚í∏‚û•Typing in dictatorshi...      False   
118825  RT @ "#MT @funder The 16 women who accused Tru...      False   
118826  RT @ "#MT @funder The 16 women who accused Tru...      False   
118827  RT @ "#MT @funder The 16 women who accused Tru...      False   
321074  RT @ ( TarekFatah ) -  EXCLUSIVE ‚Äì Linda Sar...      False   

       replyToSN                                              text2  
3116         NaN  : Typing in dictatorship #Venezuela 2017  http...  
7881         NaN  : â’¸â’¸â_¥Typing in dictatorship #Venezuela 2...  
18180        NaN  : â’¸â’¸â_¥Typing in dictatorship #Venezuela 2...  
25592        NaN  : â’¸â’¸â_¥Typing in dictatorship #Venezuela 2...  
38617        NaN  : ‰Õü‰Õü‰_´Typing in dictatorship #Venezuela 2...  
52738        NaN  : â’¸â’¸â_¥Typing in dictatorship #Venezuela 2...  
54254        NaN  : #Cine Dustin Hoffman Spars With John Oliver ...  
112149       NaN  : ‚í∏‚í∏‚û•Typing in dictatorship #Venezuela 2...  
118825       NaN   The 16 women who accused Trump of sexual assa...  
118826       NaN   The 16 women who accused Trump of sexual assa...  
118827       NaN   The 16 women who accused Trump of sexual assa...  
321074       NaN   -  EXCLUSIVE ‚Äì Linda Sarsour Allegedly Hear...

In [67]:
mention.drop('text',1,inplace=True)

In [68]:
mentioned = mention['text2'].str.extractall('@(?P<mentioned>\w+)')
mentioned

mentioned
       match                 
4      0          BetteMidler
       1        GeraldoRivera
7      0            MattLauer
16     0           CTmagazine
17     0            DanRather
19     0      realDonaldTrump
29     0            phillymag
32     0             headhntr
40     0      TheNudeReporter
46     0             AnnCurry
52     0               MLauer
60     0             DonLemon
       1       AndersonCooper
61     0                TIMEs
72     0                 TIME
83     0            emergingW
85     0                  cnn
91     0      wordpressdotcom
115    0      RepKathleenRice
117    0            IamNancyT
121    0          rosemcgowan
127    0              NBCNews
129    0           WeAreTouro
157    0            mattlauer
166    0            MattLauer
171    0          NaturaSacra
175    0            TODAYshow
       1             AnnCurry
185    0             Metro_US
188    0        normangoldman
...                       ...
392704 0              YouTube
392707 0                  CNN
392723 0                 TIME
392768 0              YouTube
392769 0              YouTube
392770 0              YouTube
392771 0              YouTube
392772 0              YouTube
392773 0              YouTube
392784 0              YouTube
392801 0       Patrick_Orouet
392849 0           SenFranken
392856 0              YouTube
392884 0              YouTube
392892 0               Medium
392923 0        Alyssa_Milano
392933 0           nakatanigo
392945 0            EdTheSock
392946 0              YouTube
392958 0      realDonaldTrump
392974 0         samunderwood
392993 0              YouTube
393020 0        HardballChris
       1      realDonaldTrump
393022 0        HuffPostWomen
393023 0              PenTV26
393024 0            BenSPLATT
393030 0            BenCaspit
393041 0            GovWalker
       1        SheriffClarke

[33123 rows x 1 columns]

Great, extraction worked. However, the returned dataframe has a multi-level index.
I just need to reset the second index

In [69]:
mentioned = mentioned.reset_index(level=1)
mentioned.head()

match      mentioned
4       0    BetteMidler
4       1  GeraldoRivera
7       0      MattLauer
16      0     CTmagazine
17      0      DanRather

In [70]:
mention[mention['tweetId'] == 2]
mention[mention['tweetId'] == 2]['text2'].values
# check that it worked

Empty DataFrame
Columns: [tweetId, screenName, isRetweet, replyToSN, text2]
Index: []

array([], dtype=object)

Great. Now I just need to join the tweetId and merge back to the dataframe 'mention'.

In [71]:
mentioned = mentioned.join(mention['tweetId'])
mentioned

match        mentioned  tweetId
4           0      BetteMidler        5
4           1    GeraldoRivera        5
7           0        MattLauer        8
16          0       CTmagazine       17
17          0        DanRather       18
19          0  realDonaldTrump       20
29          0        phillymag       30
32          0         headhntr       33
40          0  TheNudeReporter       41
46          0         AnnCurry       47
52          0           MLauer       53
60          0         DonLemon       61
60          1   AndersonCooper       61
61          0            TIMEs       62
72          0             TIME       73
83          0        emergingW       84
85          0              cnn       86
91          0  wordpressdotcom       92
115         0  RepKathleenRice      116
117         0        IamNancyT      118
121         0      rosemcgowan      122
127         0          NBCNews      128
129         0       WeAreTouro      130
157         0        mattlauer      158
166         0        MattLauer      167
171         0      NaturaSacra      172
175         0        TODAYshow      176
175         1         AnnCurry      176
185         0         Metro_US      186
188         0    normangoldman      189
...       ...              ...      ...
392704      0          YouTube   392722
392707      0              CNN   392725
392723      0             TIME   392741
392768      0          YouTube   392786
392769      0          YouTube   392787
392770      0          YouTube   392788
392771      0          YouTube   392789
392772      0          YouTube   392790
392773      0          YouTube   392791
392784      0          YouTube   392802
392801      0   Patrick_Orouet   392819
392849      0       SenFranken   392867
392856      0          YouTube   392874
392884      0          YouTube   392902
392892      0           Medium   392910
392923      0    Alyssa_Milano   392941
392933      0       nakatanigo   392951
392945      0        EdTheSock   392963
392946      0          YouTube   392964
392958      0  realDonaldTrump   392976
392974      0     samunderwood   392992
392993      0          YouTube   393011
393020      0    HardballChris   393038
393020      1  realDonaldTrump   393038
393022      0    HuffPostWomen   393040
393023      0          PenTV26   393041
393024      0        BenSPLATT   393042
393030      0        BenCaspit   393048
393041      0        GovWalker   393059
393041      1    SheriffClarke   393059

[33123 rows x 3 columns]

In [72]:
mentioned = mentioned[['tweetId', 'mentioned']]
mentioned

tweetId        mentioned
4             5      BetteMidler
4             5    GeraldoRivera
7             8        MattLauer
16           17       CTmagazine
17           18        DanRather
19           20  realDonaldTrump
29           30        phillymag
32           33         headhntr
40           41  TheNudeReporter
46           47         AnnCurry
52           53           MLauer
60           61         DonLemon
60           61   AndersonCooper
61           62            TIMEs
72           73             TIME
83           84        emergingW
85           86              cnn
91           92  wordpressdotcom
115         116  RepKathleenRice
117         118        IamNancyT
121         122      rosemcgowan
127         128          NBCNews
129         130       WeAreTouro
157         158        mattlauer
166         167        MattLauer
171         172      NaturaSacra
175         176        TODAYshow
175         176         AnnCurry
185         186         Metro_US
188         189    normangoldman
...         ...              ...
392704   392722          YouTube
392707   392725              CNN
392723   392741             TIME
392768   392786          YouTube
392769   392787          YouTube
392770   392788          YouTube
392771   392789          YouTube
392772   392790          YouTube
392773   392791          YouTube
392784   392802          YouTube
392801   392819   Patrick_Orouet
392849   392867       SenFranken
392856   392874          YouTube
392884   392902          YouTube
392892   392910           Medium
392923   392941    Alyssa_Milano
392933   392951       nakatanigo
392945   392963        EdTheSock
392946   392964          YouTube
392958   392976  realDonaldTrump
392974   392992     samunderwood
392993   393011          YouTube
393020   393038    HardballChris
393020   393038  realDonaldTrump
393022   393040    HuffPostWomen
393023   393041          PenTV26
393024   393042        BenSPLATT
393030   393048        BenCaspit
393041   393059        GovWalker
393041   393059    SheriffClarke

[33123 rows x 2 columns]

In [73]:
mention.head()

tweetId      screenName  isRetweet replyToSN  \
4         5  scottygirl2014      False       NaN   
7         8        calrican      False       NaN   
16       17  emilyjoypoetry      False       NaN   
17       18        frozenjo      False       NaN   
19       20     DougsMom204      False       NaN   

                                                text2  
4   .@BetteMidler please speak to this sexual assa...  
7   Where in the world is @MattLauer Celebrate #MeToo  
16  So I have a question. This post was published ...  
17  Im pretty sure @DanRather and Brian Williams a...  
19  How can @realDonaldTrump talk about anyone tha...

Now I need to drop 'text2' from 'mention' and merge the dataframe with 'mentioned'

In [74]:
mention.drop('text2',1,inplace=True)
mention = pd.merge(mention, mentioned, how='right', on='tweetId')
mention

tweetId       screenName  isRetweet replyToSN        mentioned
0            5   scottygirl2014      False       NaN      BetteMidler
1            5   scottygirl2014      False       NaN    GeraldoRivera
2            8         calrican      False       NaN        MattLauer
3           17   emilyjoypoetry      False       NaN       CTmagazine
4           18         frozenjo      False       NaN        DanRather
5           20      DougsMom204      False       NaN  realDonaldTrump
6           30  collegeclasses5      False       NaN        phillymag
7           33         page_lie      False       NaN         headhntr
8           41      SWSupportLV      False       NaN  TheNudeReporter
9           47        BJFrezell      False       NaN         AnnCurry
10          53  jicReneeMerling      False       NaN           MLauer
11          61    JerusalemFury      False       NaN         DonLemon
12          61    JerusalemFury      False       NaN   AndersonCooper
13          62    downrightdpad      False       NaN            TIMEs
14          73       wendy08724      False       NaN             TIME
15          84        emergingW      False       NaN        emergingW
16          86    BasedAlcatraz      False       NaN              cnn
17          92     L2MyDaughter      False       NaN  wordpressdotcom
18         116      ExMilSpouse      False       NaN  RepKathleenRice
19         118     kellyswalden      False       NaN        IamNancyT
20         122        xenakixit      False       NaN      rosemcgowan
21         128  Soumitradas4Das      False       NaN          NBCNews
22         130         hannsimp      False       NaN       WeAreTouro
23         158    DavidMcClain7      False       NaN        mattlauer
24         167        mazzou467      False       NaN        MattLauer
25         172     aplusdoubleJ      False       NaN      NaturaSacra
26         176  shannyncaldwell      False       NaN        TODAYshow
27         176  shannyncaldwell      False       NaN         AnnCurry
28         186        keftiugal      False       NaN         Metro_US
29         189     MissShuganah      False       NaN    normangoldman
...        ...              ...        ...       ...              ...
33093   392722          cavana3      False       NaN          YouTube
33094   392725    realguzzybear      False       NaN              CNN
33095   392741             Kedz      False       NaN             TIME
33096   392786     Farmer12Jane      False       NaN          YouTube
33097   392787  SantanaConsulta      False       NaN          YouTube
33098   392788     YoBuyThisNow      False       NaN          YouTube
33099   392789    ArtieSmartie1      False       NaN          YouTube
33100   392790  AmeliaImpulsive      False       NaN          YouTube
33101   392791  angie_santana20      False       NaN          YouTube
33102   392802     mvrhodes2000      False       NaN          YouTube
33103   392819    Queeenpenguin      False       NaN   Patrick_Orouet
33104   392867      MarinaGipps      False       NaN       SenFranken
33105   392874          tredf69      False       NaN          YouTube
33106   392902  Heyitsablackguy      False       NaN          YouTube
33107   392910           ZivaBF      False       NaN           Medium
33108   392941          rebel19      False       NaN    Alyssa_Milano
33109   392951           JUNP_N      False       NaN       nakatanigo
33110   392963   DrunkenStupor1      False       NaN        EdTheSock
33111   392964          LPOYSOR      False       NaN          YouTube
33112   392976      roriIZfunny      False       NaN  realDonaldTrump
33113   392992     valoriecurry      False       NaN     samunderwood
33114   393011  Carolyns_RVLife      False       NaN          YouTube
33115   393038     moosecustoms      False       NaN    HardballChris
33116   393038     moosecustoms      False       NaN  realDonaldTrump
33117   393040         mjpthol1      False       NaN    HuffPostWomen
33118   393041   

In [75]:
mention.drop(['isRetweet', 'replyToSN'],1,inplace=True)
mention.columns = ['tweetId', 'screenName', 'keyword']
mention['associationType'] = 'mention'
mention = mention[['tweetId','screenName','associationType','keyword']]
mention

tweetId       screenName associationType          keyword
0            5   scottygirl2014         mention      BetteMidler
1            5   scottygirl2014         mention    GeraldoRivera
2            8         calrican         mention        MattLauer
3           17   emilyjoypoetry         mention       CTmagazine
4           18         frozenjo         mention        DanRather
5           20      DougsMom204         mention  realDonaldTrump
6           30  collegeclasses5         mention        phillymag
7           33         page_lie         mention         headhntr
8           41      SWSupportLV         mention  TheNudeReporter
9           47        BJFrezell         mention         AnnCurry
10          53  jicReneeMerling         mention           MLauer
11          61    JerusalemFury         mention         DonLemon
12          61    JerusalemFury         mention   AndersonCooper
13          62    downrightdpad         mention            TIMEs
14          73       wendy08724         mention             TIME
15          84        emergingW         mention        emergingW
16          86    BasedAlcatraz         mention              cnn
17          92     L2MyDaughter         mention  wordpressdotcom
18         116      ExMilSpouse         mention  RepKathleenRice
19         118     kellyswalden         mention        IamNancyT
20         122        xenakixit         mention      rosemcgowan
21         128  Soumitradas4Das         mention          NBCNews
22         130         hannsimp         mention       WeAreTouro
23         158    DavidMcClain7         mention        mattlauer
24         167        mazzou467         mention        MattLauer
25         172     aplusdoubleJ         mention      NaturaSacra
26         176  shannyncaldwell         mention        TODAYshow
27         176  shannyncaldwell         mention         AnnCurry
28         186        keftiugal         mention         Metro_US
29         189     MissShuganah         mention    normangoldman
...        ...              ...             ...              ...
33093   392722          cavana3         mention          YouTube
33094   392725    realguzzybear         mention              CNN
33095   392741             Kedz         mention             TIME
33096   392786     Farmer12Jane         mention          YouTube
33097   392787  SantanaConsulta         mention          YouTube
33098   392788     YoBuyThisNow         mention          YouTube
33099   392789    ArtieSmartie1         mention          YouTube
33100   392790  AmeliaImpulsive         mention          YouTube
33101   392791  angie_santana20         mention          YouTube
33102   392802     mvrhodes2000         mention          YouTube
33103   392819    Queeenpenguin         mention   Patrick_Orouet
33104   392867      MarinaGipps         mention       SenFranken
33105   392874          tredf69         mention          YouTube
33106   392902  Heyitsablackguy         mention          YouTube
33107   392910           ZivaBF         mention           Medium
33108   392941          rebel19         mention    Alyssa_Milano
33109   392951           JUNP_N         mention       nakatanigo
33110   392963   DrunkenStupor1         mention        EdTheSock
33111   392964          LPOYSOR         mention          YouTube
33112   392976      roriIZfunny         mention  realDonaldTrump
33113   392992     valoriecurry         mention     samunderwood
33114   393011  Carolyns_RVLife         mention          YouTube
33115   393038     moosecustoms         mention    HardballChris
33116   393038     moosecustoms         mention  realDonaldTrump
33117   393040         mjpthol1         mention    HuffPostWomen
33118   393041    closethegapCA         mention          PenTV26
33119   393042    Ruthie_Murray         mention        BenSPLATT
33120   393048       MazenMahdi         mention        BenCaspit
33121   393059    onejimharris_         mention        GovWalker
33122   393059    onejimharris_         me

## Self

In [76]:
self = df[['tweetId','screenName', 'text', 'isRetweet', 'replyToSN']]

In [77]:
self = self[self['replyToSN'].isnull() & (self['isRetweet'] == False)]
self

tweetId       screenName  \
0             1        ahmediaTV   
2             3   DemerisePotvin   
3             4     TheDawnStott   
4             5   scottygirl2014   
5             6     ForEverBrenn   
6             7   silveriaalison   
7             8         calrican   
10           11      BrunusCutis   
11           12       RDonSteele   
13           14         dbehan79   
14           15       european_4   
15           16  FrancescaBiller   
16           17   emilyjoypoetry   
17           18         frozenjo   
18           19         num1_fan   
19           20      DougsMom204   
20           21         page_lie   
23           24      justshocked   
25           26   womanontheleft   
26           27        JessLivMo   
27           28          JC4ever   
28           29       european_4   
29           30  collegeclasses5   
30           31        BRellator   
32           33         page_lie   
33           34      J_R_Kestner   
36           37        GLucivero   
37           38       IndigoRave   
39           40        AliBerlow   
40           41      SWSupportLV   
...         ...              ...   
393010   393028   DougThorpe_com   
393012   393030  VictoriaHagstr2   
393017   393035  phillygodfather   
393018   393036           TheCut   
393020   393038     moosecustoms   
393022   393040         mjpthol1   
393023   393041    closethegapCA   
393024   393042    Ruthie_Murray   
393026   393044        HeloJapes   
393028   393046     KarmicAction   
393030   393048       MazenMahdi   
393036   393054          Bode834   
393041   393059    onejimharris_   
393044   393062    davidwood1121   
393045   393063  lordioushulaio1   
393052   393070      Elisheva_CA   
393053   393071   MermaidsMatter   
393054   393072      MeggyLepepe   
393056   393074        baxter375   
393062   393080  metsubokumatsur   
393070   393088       CDMitchell   
393081   393099         TIFF_NET   
393091   393109      JamesEFinch   
393093   393111       book_tribe   
393095   393113       ruby_wine_   
393098   393116      PeterFeaman   
393107   393125        EINITNews   
393114   393132   April_Magazine   
393115   393133         Noofer55   
393117   393135         pewdrdad   

                                                     text  isRetweet replyToSN  
0         American Harem.. #MeToo https://t.co/HjExLJdGuF      False       NaN  
2       Watched Megan Kelly ask Joe Keery this A.M. if...      False       NaN  
3       Women have been talking about this crap the en...      False       NaN  
4       .@BetteMidler please speak to this sexual assa...      False       NaN  
5       We can't keep turning a blind eye and pretend ...      False       NaN  
6       Jay-Z is saying what I've been saying. DJT's j...      False       NaN  
7       Where in the world is @MattLauer Celebrate #MeToo      False       NaN  
10      Is it just me or does the #MeToo <----icon; fr...      False       NaN  
11      Just  got scammed out of  $25.  Bought #TigerW...      False       NaN  
13                   #BlackLivesMatter with #MeToo yup ok      False       NaN  
14      Why are not the men haters from #Metoo marchin...      False       NaN  
15      I was sexually harassed as a "young Intern" fo...      False       NaN  
16      So I have a question. This post was published ...      False       NaN  
17      Im pretty sure @DanRather and Brian Williams a...      False       NaN  
18      Aint trying to start nothing but wouldnt it be...      False       NaN  
19      How can @realDonaldTrump talk about anyone tha...      False       NaN  
20      Yes!! WHEN it happens to you, THEN you can dec...      False       NaN  
23      men all over this country are seeking ways to ...      False       NaN  
25      Geraldo Rivera says "news is a flirty business...      False       NaN  
26      Political men: it is only a matter of time. #M...      False       NaN  
27      How do you reconcile your love of someone if t...      False      

In [78]:
self = self[self['text'].str.contains('@') == False]
self

tweetId       screenName  \
0             1        ahmediaTV   
2             3   DemerisePotvin   
3             4     TheDawnStott   
5             6     ForEverBrenn   
6             7   silveriaalison   
10           11      BrunusCutis   
11           12       RDonSteele   
13           14         dbehan79   
14           15       european_4   
15           16  FrancescaBiller   
18           19         num1_fan   
20           21         page_lie   
23           24      justshocked   
25           26   womanontheleft   
26           27        JessLivMo   
27           28          JC4ever   
28           29       european_4   
30           31        BRellator   
33           34      J_R_Kestner   
36           37        GLucivero   
37           38       IndigoRave   
39           40        AliBerlow   
41           42    missremington   
42           43    rachelndeleon   
43           44     Meamoore1391   
45           46     ChanaDoreaux   
47           48  CatherinesIdaho   
48           49          BekLiza   
49           50   spikybluealien   
50           51         cnntoday   
...         ...              ...   
392990   393008       gclarence1   
392991   393009      SportsAloud   
392992   393010  georgiaritterUK   
392995   393013  hamiltoncreator   
393006   393024         FilmGodd   
393007   393025         MrsDandD   
393010   393028   DougThorpe_com   
393012   393030  VictoriaHagstr2   
393017   393035  phillygodfather   
393018   393036           TheCut   
393026   393044        HeloJapes   
393028   393046     KarmicAction   
393036   393054          Bode834   
393044   393062    davidwood1121   
393045   393063  lordioushulaio1   
393052   393070      Elisheva_CA   
393053   393071   MermaidsMatter   
393054   393072      MeggyLepepe   
393056   393074        baxter375   
393062   393080  metsubokumatsur   
393070   393088       CDMitchell   
393081   393099         TIFF_NET   
393091   393109      JamesEFinch   
393093   393111       book_tribe   
393095   393113       ruby_wine_   
393098   393116      PeterFeaman   
393107   393125        EINITNews   
393114   393132   April_Magazine   
393115   393133         Noofer55   
393117   393135         pewdrdad   

                                                     text  isRetweet replyToSN  
0         American Harem.. #MeToo https://t.co/HjExLJdGuF      False       NaN  
2       Watched Megan Kelly ask Joe Keery this A.M. if...      False       NaN  
3       Women have been talking about this crap the en...      False       NaN  
5       We can't keep turning a blind eye and pretend ...      False       NaN  
6       Jay-Z is saying what I've been saying. DJT's j...      False       NaN  
10      Is it just me or does the #MeToo <----icon; fr...      False       NaN  
11      Just  got scammed out of  $25.  Bought #TigerW...      False       NaN  
13                   #BlackLivesMatter with #MeToo yup ok      False       NaN  
14      Why are not the men haters from #Metoo marchin...      False       NaN  
15      I was sexually harassed as a "young Intern" fo...      False       NaN  
18      Aint trying to start nothing but wouldnt it be...      False       NaN  
20      Yes!! WHEN it happens to you, THEN you can dec...      False       NaN  
23      men all over this country are seeking ways to ...      False       NaN  
25      Geraldo Rivera says "news is a flirty business...      False       NaN  
26      Political men: it is only a matter of time. #M...      False       NaN  
27      How do you reconcile your love of someone if t...      False       NaN  
28      I was patting my cat when she left my laps sud...      False       NaN  
30      Geraldo Rivera...  Me thinks you're next buddy...      False       NaN  
33      The bad behavior getting exposed in Hollywood ...      False       NaN  
36      Is it ever appropriate to yell show us your ti...      False       NaN  
37      and the reality  that many of us have been liv...      False      

In [79]:
self.drop(['isRetweet', 'replyToSN', 'text'],1,inplace=True)

In [80]:
self

tweetId       screenName
0             1        ahmediaTV
2             3   DemerisePotvin
3             4     TheDawnStott
5             6     ForEverBrenn
6             7   silveriaalison
10           11      BrunusCutis
11           12       RDonSteele
13           14         dbehan79
14           15       european_4
15           16  FrancescaBiller
18           19         num1_fan
20           21         page_lie
23           24      justshocked
25           26   womanontheleft
26           27        JessLivMo
27           28          JC4ever
28           29       european_4
30           31        BRellator
33           34      J_R_Kestner
36           37        GLucivero
37           38       IndigoRave
39           40        AliBerlow
41           42    missremington
42           43    rachelndeleon
43           44     Meamoore1391
45           46     ChanaDoreaux
47           48  CatherinesIdaho
48           49          BekLiza
49           50   spikybluealien
50           51         cnntoday
...         ...              ...
392990   393008       gclarence1
392991   393009      SportsAloud
392992   393010  georgiaritterUK
392995   393013  hamiltoncreator
393006   393024         FilmGodd
393007   393025         MrsDandD
393010   393028   DougThorpe_com
393012   393030  VictoriaHagstr2
393017   393035  phillygodfather
393018   393036           TheCut
393026   393044        HeloJapes
393028   393046     KarmicAction
393036   393054          Bode834
393044   393062    davidwood1121
393045   393063  lordioushulaio1
393052   393070      Elisheva_CA
393053   393071   MermaidsMatter
393054   393072      MeggyLepepe
393056   393074        baxter375
393062   393080  metsubokumatsur
393070   393088       CDMitchell
393081   393099         TIFF_NET
393091   393109      JamesEFinch
393093   393111       book_tribe
393095   393113       ruby_wine_
393098   393116      PeterFeaman
393107   393125        EINITNews
393114   393132   April_Magazine
393115   393133         Noofer55
393117   393135         pewdrdad

[93305 rows x 2 columns]

In [81]:
self['associationType'] = 'self'
self['keyword'] = np.nan
self

tweetId       screenName associationType  keyword
0             1        ahmediaTV            self      NaN
2             3   DemerisePotvin            self      NaN
3             4     TheDawnStott            self      NaN
5             6     ForEverBrenn            self      NaN
6             7   silveriaalison            self      NaN
10           11      BrunusCutis            self      NaN
11           12       RDonSteele            self      NaN
13           14         dbehan79            self      NaN
14           15       european_4            self      NaN
15           16  FrancescaBiller            self      NaN
18           19         num1_fan            self      NaN
20           21         page_lie            self      NaN
23           24      justshocked            self      NaN
25           26   womanontheleft            self      NaN
26           27        JessLivMo            self      NaN
27           28          JC4ever            self      NaN
28           29       european_4            self      NaN
30           31        BRellator            self      NaN
33           34      J_R_Kestner            self      NaN
36           37        GLucivero            self      NaN
37           38       IndigoRave            self      NaN
39           40        AliBerlow            self      NaN
41           42    missremington            self      NaN
42           43    rachelndeleon            self      NaN
43           44     Meamoore1391            self      NaN
45           46     ChanaDoreaux            self      NaN
47           48  CatherinesIdaho            self      NaN
48           49          BekLiza            self      NaN
49           50   spikybluealien            self      NaN
50           51         cnntoday            self      NaN
...         ...              ...             ...      ...
392990   393008       gclarence1            self      NaN
392991   393009      SportsAloud            self      NaN
392992   393010  georgiaritterUK            self      NaN
392995   393013  hamiltoncreator            self      NaN
393006   393024         FilmGodd            self      NaN
393007   393025         MrsDandD            self      NaN
393010   393028   DougThorpe_com            self      NaN
393012   393030  VictoriaHagstr2            self      NaN
393017   393035  phillygodfather            self      NaN
393018   393036           TheCut            self      NaN
393026   393044        HeloJapes            self      NaN
393028   393046     KarmicAction            self      NaN
393036   393054          Bode834            self      NaN
393044   393062    davidwood1121            self      NaN
393045   393063  lordioushulaio1            self      NaN
393052   393070      Elisheva_CA            self      NaN
393053   393071   MermaidsMatter            self      NaN
393054   393072      MeggyLepepe            self      NaN
393056   393074        baxter375            self      NaN
393062   393080  metsubokumatsur            self      NaN
393070   393088       CDMitchell            self      NaN
393081   393099         TIFF_NET            self      NaN
393091   393109      JamesEFinch            self      NaN
393093   393111       book_tribe            self      NaN
393095   393113       ruby_wine_            self      NaN
393098   393116      PeterFeaman            self      NaN
393107   393125        EINITNews            self      NaN
393114   393132   April_Magazine            self      NaN
393115   393133         Noofer55            self      NaN
393117   393135         pewdrdad            self      NaN

[93305 rows x 4 columns]

## Merge associations

In [82]:
associations = pd.concat([mention, retweet, reply, self])
len(associations) == len(self) + len(mention) + len(retweet) + len(reply)

True

In [83]:
# sort by tweetId
associations.sort_values('tweetId', inplace=True)
associations = associations.reset_index(drop=True)

# before exporting, I'm going to assign unique IDs again
associations['associationId'] = np.arange(1, len(associations)+1)

# reorder columns
associations = associations[['associationId', 'tweetId', 'screenName', 'associationType', 'keyword']]
associations

associationId  tweetId       screenName associationType  \
0                   1        1        ahmediaTV            self   
1                   2        2   JesusPrepper74           reply   
2                   3        3   DemerisePotvin            self   
3                   4        4     TheDawnStott            self   
4                   5        5   scottygirl2014         mention   
5                   6        5   scottygirl2014         mention   
6                   7        6     ForEverBrenn            self   
7                   8        7   silveriaalison            self   
8                   9        8         calrican         mention   
9                  10        9   traugott_sarah           reply   
10                 11       10  SchifanoRaelene           reply   
11                 12       11      BrunusCutis            self   
12                 13       12       RDonSteele            self   
13                 14       13     _standeliver           reply   
14                 15       14         dbehan79            self   
15                 16       15       european_4            self   
16                 17       16  FrancescaBiller            self   
17                 18       17   emilyjoypoetry         mention   
18                 19       18         frozenjo         mention   
19                 20       19         num1_fan            self   
20                 21       20      DougsMom204         mention   
21                 22       21         page_lie            self   
22                 23       22  VirginiusPrimus           reply   
23                 24       23       1mimi4ever           reply   
24                 25       24      justshocked            self   
25                 26       25    ProphetPhella           reply   
26                 27       26   womanontheleft            self   
27                 28       27        JessLivMo            self   
28                 29       28          JC4ever            self   
29                 30       29       european_4            self   
...               ...      ...              ...             ...   
398114         398115   393106   writerincanada         retweet   
398115         398116   393107    ellimayradrep         retweet   
398116         398117   393108  viniciusnikolod         retweet   
398117         398118   393109      JamesEFinch            self   
398118         398119   393110         nscrowba         retweet   
398119         398120   393111       book_tribe            self   
398120         398121   393112         jp_flyer           reply   
398121         398122   393113       ruby_wine_            self   
398122         398123   393114      DebraRobbin         retweet   
398123         398124   393115      StevenGuggs         retweet   
398124         398125   393116      PeterFeaman            self   
398125         398126   393117  Tucs0nMortgages         retweet   
398126         398127   393118  tlacovaspravask         retweet   
398127         398128   393119      King17Larry         retweet   
398128         398129   393120         Rparisee         retweet   
398129         398130   393121        Adam_Eire           reply   
398130         398131   393122   mikefreemanNFL         retweet   
398131         398132   393123        tomcat159         retweet   
398132         398133   393124     Zwoodbutcher         retweet   
398133         398134   393125        EINITNews            self   
398134         398135   393126   AlgerianPalest         retweet   
398135         398136   393127    kingofponders         retweet   
398136         398137   393128      KosPatricia         retweet   
398137         398138   393129     TwittaChicca         retweet   
398138         398139   393130   BuffyLibSlayer         retweet   
398139         398140   393131       boaomega22         retweet   
398140         398141   393132   April_Magazine            self   
398141         398142   393133         Noofer55        

In [84]:
associations.to_csv('Data/associations.csv', index=False)

## Complete users dataset

In [85]:
users = pd.read_csv('Data/users.csv')

In [86]:
# Extract all unique users that were mentioned/retweeted/responded, that are not in the users.csv file
unique = associations[associations['associationType'] != 'hashtag']['keyword'].unique()
unique = pd.DataFrame(unique, columns = ['screenName'])

In [87]:
np.logical_not(unique['screenName'].isin(users['screenName'])).value_counts()

False    21628
True     18693
Name: screenName, dtype: int64

There are 25329 users that were referenced in the tweets, whose tweets are not in our dataset.<br>
This is great because about 50% of tweets references users that are already in the data, which enables us to visualize the virality.<br>
Now let's add these users to the csv file

In [88]:
unique = unique[np.logical_not(unique['screenName'].isin(users['screenName']))]
unique
# users that are not included in our dataset as part of users.csv

screenName
0                  NaN
1        johnconyersjr
2          BetteMidler
3        GeraldoRivera
4            MattLauer
5           JoyAnnReid
6         RepAdamSmith
7      RepKathleenRice
9            DanRather
10     realDonaldTrump
12         SaveUSA1776
15            headhntr
16          samaralynn
19            AnnCurry
20              MLauer
23      AndersonCooper
24            DonLemon
25               TIMEs
27            SebGorka
30         CoachTDavis
33                 cnn
35          Joyannah73
36     wordpressdotcom
40         Breaking911
43         rosemcgowan
44         SpeakerRyan
47          WeAreTouro
49      MonicaLewinsky
53               USAID
56           counosboy
...                ...
40269          Freeset
40270          kmeinke
40272        JordanUhl
40273    banzetsuatabo
40274     BarryJenkins
40277  convergingpersp
40282    gregmortenson
40285     JamesTHarris
40286         GSinghPb
40287       RainwayApp
40288        tsnotoole
40292     bareMinerals
40294  JohnMichaels929
40295    putemupcdukes
40296  Real_Dan_Joseph
40298    VeganYogaDude
40302   Misstabstevens
40303       nakatanigo
40304  Cleverestcookie
40305        EdTheSock
40307     joyellen1962
40309     samunderwood
40312          PenTV26
40313  BonnieEisenberg
40314  HereComesTreb1e
40315     _Emmet_Emmet
40316           remoca
40317         N_Fatale
40319      VanillaLady
40320          Jaguars

[18693 rows x 1 columns]

In [89]:
print(f'{len(users)} - # of unique users already in our dataset')
print(f'{len(unique)} - # of unique users not in dataset')
print(f'{len(users) + len(unique)} - # of unique users in dataset after adding these new users')

users = pd.concat([users, unique])
users

222311 - # of unique users already in our dataset
18693 - # of unique users not in dataset
241004 - # of unique users in dataset after adding these new users


screenName
0            ahmediaTV
1       JesusPrepper74
2       DemerisePotvin
3         TheDawnStott
4       scottygirl2014
5         ForEverBrenn
6       silveriaalison
7             calrican
8       traugott_sarah
9      SchifanoRaelene
10         BrunusCutis
11          RDonSteele
12        _standeliver
13            dbehan79
14          european_4
15     FrancescaBiller
16      emilyjoypoetry
17            frozenjo
18            num1_fan
19         DougsMom204
20            page_lie
21     VirginiusPrimus
22          1mimi4ever
23         justshocked
24       ProphetPhella
25      womanontheleft
26           JessLivMo
27             JC4ever
28     collegeclasses5
29           BRellator
...                ...
40269          Freeset
40270          kmeinke
40272        JordanUhl
40273    banzetsuatabo
40274     BarryJenkins
40277  convergingpersp
40282    gregmortenson
40285     JamesTHarris
40286         GSinghPb
40287       RainwayApp
40288        tsnotoole
40292     bareMinerals
40294  JohnMichaels929
40295    putemupcdukes
40296  Real_Dan_Joseph
40298    VeganYogaDude
40302   Misstabstevens
40303       nakatanigo
40304  Cleverestcookie
40305        EdTheSock
40307     joyellen1962
40309     samunderwood
40312          PenTV26
40313  BonnieEisenberg
40314  HereComesTreb1e
40315     _Emmet_Emmet
40316           remoca
40317         N_Fatale
40319      VanillaLady
40320          Jaguars

[241004 rows x 1 columns]

In [90]:
users.drop_duplicates(inplace=True)
users.to_csv('Data/users.csv', index=False)

## Update: found a NaN in the downloaded data

In [91]:
import pandas as pd

In [92]:
associations = pd.read_csv('Data/associations.csv')
users = pd.read_csv('Data/users.csv')

In [93]:
df = pd.read_csv('Data/tweets.csv')

In [94]:
associations.isnull().sum()

associationId          0
tweetId                0
screenName             0
associationType        0
keyword            93305
dtype: int64

In [95]:
users.isnull().sum()

screenName    1
dtype: int64

In [96]:
df.isnull().sum()

tweetId               0
screenName            0
text                  0
replyToSN        343402
isRetweet             0
retweeted             0
retweetCount          0
favorited             0
favoriteCount         0
truncated             0
created               0
statusSource          3
longitude        392995
latitude         392995
dtype: int64

In [97]:
# we need to drop NaN values in users

In [98]:
users[users['screenName'].isnull()]

screenName
222311        NaN

In [99]:
len(users)

241004

In [100]:
users.dropna(subset=['screenName'],inplace=True)
len(users)

241003

In [101]:
users[users['screenName'].isnull()]

Empty DataFrame
Columns: [screenName]
Index: []

In [102]:
users.to_csv('Data/users.csv', index=False)

# Interactions

In [103]:
associations = pd.read_csv('Data/associations.csv')
associations

associationId  tweetId       screenName associationType  \
0                   1        1        ahmediaTV            self   
1                   2        2   JesusPrepper74           reply   
2                   3        3   DemerisePotvin            self   
3                   4        4     TheDawnStott            self   
4                   5        5   scottygirl2014         mention   
5                   6        5   scottygirl2014         mention   
6                   7        6     ForEverBrenn            self   
7                   8        7   silveriaalison            self   
8                   9        8         calrican         mention   
9                  10        9   traugott_sarah           reply   
10                 11       10  SchifanoRaelene           reply   
11                 12       11      BrunusCutis            self   
12                 13       12       RDonSteele            self   
13                 14       13     _standeliver           reply   
14                 15       14         dbehan79            self   
15                 16       15       european_4            self   
16                 17       16  FrancescaBiller            self   
17                 18       17   emilyjoypoetry         mention   
18                 19       18         frozenjo         mention   
19                 20       19         num1_fan            self   
20                 21       20      DougsMom204         mention   
21                 22       21         page_lie            self   
22                 23       22  VirginiusPrimus           reply   
23                 24       23       1mimi4ever           reply   
24                 25       24      justshocked            self   
25                 26       25    ProphetPhella           reply   
26                 27       26   womanontheleft            self   
27                 28       27        JessLivMo            self   
28                 29       28          JC4ever            self   
29                 30       29       european_4            self   
...               ...      ...              ...             ...   
398114         398115   393106   writerincanada         retweet   
398115         398116   393107    ellimayradrep         retweet   
398116         398117   393108  viniciusnikolod         retweet   
398117         398118   393109      JamesEFinch            self   
398118         398119   393110         nscrowba         retweet   
398119         398120   393111       book_tribe            self   
398120         398121   393112         jp_flyer           reply   
398121         398122   393113       ruby_wine_            self   
398122         398123   393114      DebraRobbin         retweet   
398123         398124   393115      StevenGuggs         retweet   
398124         398125   393116      PeterFeaman            self   
398125         398126   393117  Tucs0nMortgages         retweet   
398126         398127   393118  tlacovaspravask         retweet   
398127         398128   393119      King17Larry         retweet   
398128         398129   393120         Rparisee         retweet   
398129         398130   393121        Adam_Eire           reply   
398130         398131   393122   mikefreemanNFL         retweet   
398131         398132   393123        tomcat159         retweet   
398132         398133   393124     Zwoodbutcher         retweet   
398133         398134   393125        EINITNews            self   
398134         398135   393126   AlgerianPalest         retweet   
398135         398136   393127    kingofponders         retweet   
398136         398137   393128      KosPatricia         retweet   
398137         398138   393129     TwittaChicca         retweet   
398138         398139   393130   BuffyLibSlayer         retweet   
398139         398140   393131       boaomega22         retweet   
398140         398141   393132   April_Magazine            self   
398141         398142   393133         Noofer55        

Just noticed that for every user that received a reply, that user is also included as 'mention'.<br>
I did some quick research on the types of tweets that we are dealing with<br>
<hr>
Source: https://www.adweek.com/digital/reply-mention/

**Tweets That Start With @Username**

Any tweet that starts with @username on Twitter is interpreted as a reply – that is, Twitter assumes you’re sending this message directly to that person and will place it in their feed (and mentions folder) accordingly.

It’s still a public message (as opposed to a private direct message), and is visible when anyone visits the sender’s profile page. However (and this is the kicker), **if you start a message with @username, it won’t appear in the standard home stream of anyone else in your network** unless both of you (the sender and the recipient) are being followed.

**Tweets That Place @Username Somewhere Else**

If a given @username is included in a tweet anywhere else but at the very start, Twitter interprets this differently – as a mention instead of a reply.

What this means is that the tweet will be immediately sent to the home stream of everyone who is following you, and not just the person that was mentioned.

Put literally anything ahead of the @ symbol on a tweet and it isn’t a reply. This is why you see some users placing a full stop before the @username (i.e., .@username), often when they’ve been asked to respond to a given question multiple times by different people, as this allows them to mass-broadcast a “reply” to everybody while also (seemingly) responding directly to the last person who made the enquiry.

A kind of faux reply, if you will. I don’t recommend it. If you want to make an open tweet, then make an open tweet (and tag at the end if necessary). Don’t try and disguise it as something else. It’s confusing enough for newcomers as it is.
<hr>
First, I want to focus on analyzing how the movement grew and spread, so we will exclude replies for now.

In [104]:
tweets = pd.read_csv('Data/tweets.csv')
users = pd.read_csv('Data/users.csv')

In [105]:
tweets

tweetId       screenName  \
0             1        ahmediaTV   
1             2   JesusPrepper74   
2             3   DemerisePotvin   
3             4     TheDawnStott   
4             5   scottygirl2014   
5             6     ForEverBrenn   
6             7   silveriaalison   
7             8         calrican   
8             9   traugott_sarah   
9            10  SchifanoRaelene   
10           11      BrunusCutis   
11           12       RDonSteele   
12           13     _standeliver   
13           14         dbehan79   
14           15       european_4   
15           16  FrancescaBiller   
16           17   emilyjoypoetry   
17           18         frozenjo   
18           19         num1_fan   
19           20      DougsMom204   
20           21         page_lie   
21           22  VirginiusPrimus   
22           23       1mimi4ever   
23           24      justshocked   
24           25    ProphetPhella   
25           26   womanontheleft   
26           27        JessLivMo   
27           28          JC4ever   
28           29       european_4   
29           30  collegeclasses5   
...         ...              ...   
393088   393106   writerincanada   
393089   393107    ellimayradrep   
393090   393108  viniciusnikolod   
393091   393109      JamesEFinch   
393092   393110         nscrowba   
393093   393111       book_tribe   
393094   393112         jp_flyer   
393095   393113       ruby_wine_   
393096   393114      DebraRobbin   
393097   393115      StevenGuggs   
393098   393116      PeterFeaman   
393099   393117  Tucs0nMortgages   
393100   393118  tlacovaspravask   
393101   393119      King17Larry   
393102   393120         Rparisee   
393103   393121        Adam_Eire   
393104   393122   mikefreemanNFL   
393105   393123        tomcat159   
393106   393124     Zwoodbutcher   
393107   393125        EINITNews   
393108   393126   AlgerianPalest   
393109   393127    kingofponders   
393110   393128      KosPatricia   
393111   393129     TwittaChicca   
393112   393130   BuffyLibSlayer   
393113   393131       boaomega22   
393114   393132   April_Magazine   
393115   393133         Noofer55   
393116   393134           ZBezzt   
393117   393135         pewdrdad   

                                                     text        replyToSN  \
0         American Harem.. #MeToo https://t.co/HjExLJdGuF              NaN   
1       @johnconyersjr  @alfranken  why have you guys ...    johnconyersjr   
2       Watched Megan Kelly ask Joe Keery this A.M. if...              NaN   
3       Women have been talking about this crap the en...              NaN   
4       .@BetteMidler please speak to this sexual assa...              NaN   
5       We can't keep turning a blind eye and pretend ...              NaN   
6       Jay-Z is saying what I've been saying. DJT's j...              NaN   
7       Where in the world is @MattLauer Celebrate #MeToo              NaN   
8              @JoyAnnReid Keep it coming ladies!  #MeToo       JoyAnnReid   
9       @RepAdamSmith Workplace is one place, but what...     RepAdamSmith   
10      Is it just me or does the #MeToo <----icon; fr...              NaN   
11      Just  got scammed out of  $25.  Bought #TigerW...              NaN   
12      @RepKathleenRice @RepJayapal Calling out @RepJ...  RepKathleenRice   
13                   #BlackLivesMatter with #MeToo yup ok              NaN   
14      Why are not the men haters from #Metoo marchin...              NaN   
15      I was sexually harassed as a "young Intern" fo...              NaN   
16      So I have a question. This post was published ...              NaN   
17      Im pretty sure @DanRather and Brian Williams a...              NaN   
18      Aint trying to start nothing but wouldnt it be...              NaN   
19      How can @realDonaldTrump talk about anyone tha...              NaN   
20      Yes!! WHEN it happens to you, THEN you can dec...              NaN   
21      @CNN Read: "we must destroy the oppressive pat...  

In [106]:
tweets[tweets['tweetId'] == 2]['text'].values

array(['@johnconyersjr  @alfranken  why have you guys not resigned yet? Liberal hypocrisy! #MeToo'],
      dtype=object)

In [107]:
len(tweets[np.logical_not(tweets['replyToSN'].isnull())]) == len(tweets[tweets['text'].str.startswith('@')])

False

In [108]:
# tweets where 'replyToSN' and the first character of the text did not agree 
# (reply that didn't start with "@", vice versa)
tweets[np.logical_not(tweets['replyToSN'].isnull()) != tweets['text'].str.startswith('@')]

tweetId       screenName  \
34           35      ThalesLives   
105         106   LilMissRightie   
200         201    NoHopeCitizen   
205         206        Unitynow8   
229         230      EzraFitz_13   
308         309       frenchcori   
359         360            b9AcE   
390         391  Webbedspiderrob   
391         392        ejgibbens   
426         427        StuckonSW   
485         486   BooksbySSJaxon   
544         545    lurvejennifer   
549         550       AnaMardoll   
578         579   TobsonHelsinki   
647         648            b9AcE   
740         741       frenchcori   
746         747          AJDMaru   
750         751   OverTheMoonbat   
751         752   JeremyMcLellan   
774         775      EzraFitz_13   
972         973        NolanHack   
975         976  catladypolitics   
1010       1011   forbiddencomma   
1055       1056      Charmed0504   
1128       1129     WilliarMedic   
1276       1277    CrankyOldBats   
1356       1357    ktullymcmanus   
1431       1432    mauraacarroll   
1434       1435      yrfatfriend   
1490       1491   chelliepingree   
...         ...              ...   
389372   389378    peterhoneyman   
389536   389542         VVandvik   
389744   389754  ScholarNagaMama   
389825   389837      MrGCampbell   
389827   389839      MrGCampbell   
389990   390003  JonathanAconomy   
390125   390138      EzraFitz_13   
390353   390366      EzraFitz_13   
390483   390496   XhN_XvieR_XyZa   
390558   390571       laurenbaer   
390693   390706        AnneArdon   
391448   391466      EzraFitz_13   
391552   391570      EzraFitz_13   
391587   391605    TheGamblingQB   
391634   391652        GitGirl89   
391678   391696            Que3M   
391703   391721       JGibsonDem   
391742   391760  NicoleScioville   
391817   391835    SarahSchwartz   
391843   391861         HillYes1   
391868   391886      xkristi_kat   
392022   392040   NewEnglander34   
392323   392341   Mike4LibertyTX   
392403   392421      victorymonk   
392544   392562  UncleChanBlake2   
392685   392703       lucyoopsie   
392692   392710     JackPolakoff   
392696   392714       lucyoopsie   
392968   392986      EzraFitz_13   
392977   392995  DiederikKramers   

                                                     text        replyToSN  \
34      8. But how soon before this snowball of sexual...      ThalesLives   
105     Forget #MeToo for now or for just a moment and...   LilMissRightie   
200     @MLauer picks on @POTUS for a discussion with ...              NaN   
205     @LanaDelRaytheon Also were do I bet on how man...              NaN   
229     RT lucas_megatron: Meghan_Trainor just this On...      EzraFitz_13   
308     #MeToo reminds me of that awkward, uncomfortab...       frenchcori   
359     Astonishing that AFAIK, there hasn't been any ...            b9AcE   
390     For most of these accusations, there is little...  Webbedspiderrob   
391     Next up on the #metoo playlist - Fuck You by L...        ejgibbens   
426     America: The #MeToo movement has been a waters...        StuckonSW   
485     For we cannot tarry here; We must fight my dar...   BooksbySSJaxon   
544     @MLauer I'm beside myself with anger and disgu...              NaN   
549     I'm just incredibly tired of people saying "oh...       AnaMardoll   
578     I wondered how long it would take for Finnish ...   TobsonHelsinki   
647     Swedish public service TV news this evening: "...            b9AcE   
740     Im about to retire. And as I look back, I am r...       frenchcori   
746     I miss Barbara Walters. She's ill and in hidin...          AJDMaru   
750     "#MeToo" -- #ProblematicWomen #RedPillBlack .....   OverTheMoonbat   
751     I know at least a dozen of my friends have men...   JeremyMcLellan   
774     Meghan_charts Dear Future Husband y Better uwu...      EzraFitz_13   
972     "Racism is the norm in our society and sexism ...        NolanHack   
975     Feminism isn't a dirty word and feminists aren...  

Seems like there are 2 rare cases 
* 1. users can reply to tweets without beginning their tweets with username of the intended audience (person being replied to)
* 2. users can begin their tweets with "@" followed by the username of the intended audience, and still not be recognized as a reply

In [109]:
# case #1
tweets[np.logical_not(tweets['replyToSN'].isnull()) & np.logical_not(tweets['text'].str.startswith('@'))]

tweetId       screenName  \
34           35      ThalesLives   
105         106   LilMissRightie   
229         230      EzraFitz_13   
308         309       frenchcori   
359         360            b9AcE   
390         391  Webbedspiderrob   
391         392        ejgibbens   
426         427        StuckonSW   
485         486   BooksbySSJaxon   
549         550       AnaMardoll   
578         579   TobsonHelsinki   
647         648            b9AcE   
740         741       frenchcori   
746         747          AJDMaru   
750         751   OverTheMoonbat   
751         752   JeremyMcLellan   
774         775      EzraFitz_13   
972         973        NolanHack   
975         976  catladypolitics   
1010       1011   forbiddencomma   
1055       1056      Charmed0504   
1128       1129     WilliarMedic   
1276       1277    CrankyOldBats   
1356       1357    ktullymcmanus   
1431       1432    mauraacarroll   
1434       1435      yrfatfriend   
1490       1491   chelliepingree   
1611       1612  VillageBelle256   
1759       1760         Gr8Melin   
1767       1768        Dougie21z   
...         ...              ...   
389372   389378    peterhoneyman   
389536   389542         VVandvik   
389744   389754  ScholarNagaMama   
389825   389837      MrGCampbell   
389827   389839      MrGCampbell   
389990   390003  JonathanAconomy   
390125   390138      EzraFitz_13   
390353   390366      EzraFitz_13   
390483   390496   XhN_XvieR_XyZa   
390558   390571       laurenbaer   
390693   390706        AnneArdon   
391448   391466      EzraFitz_13   
391552   391570      EzraFitz_13   
391587   391605    TheGamblingQB   
391634   391652        GitGirl89   
391678   391696            Que3M   
391703   391721       JGibsonDem   
391742   391760  NicoleScioville   
391817   391835    SarahSchwartz   
391843   391861         HillYes1   
391868   391886      xkristi_kat   
392022   392040   NewEnglander34   
392323   392341   Mike4LibertyTX   
392403   392421      victorymonk   
392544   392562  UncleChanBlake2   
392685   392703       lucyoopsie   
392692   392710     JackPolakoff   
392696   392714       lucyoopsie   
392968   392986      EzraFitz_13   
392977   392995  DiederikKramers   

                                                     text        replyToSN  \
34      8. But how soon before this snowball of sexual...      ThalesLives   
105     Forget #MeToo for now or for just a moment and...   LilMissRightie   
229     RT lucas_megatron: Meghan_Trainor just this On...      EzraFitz_13   
308     #MeToo reminds me of that awkward, uncomfortab...       frenchcori   
359     Astonishing that AFAIK, there hasn't been any ...            b9AcE   
390     For most of these accusations, there is little...  Webbedspiderrob   
391     Next up on the #metoo playlist - Fuck You by L...        ejgibbens   
426     America: The #MeToo movement has been a waters...        StuckonSW   
485     For we cannot tarry here; We must fight my dar...   BooksbySSJaxon   
549     I'm just incredibly tired of people saying "oh...       AnaMardoll   
578     I wondered how long it would take for Finnish ...   TobsonHelsinki   
647     Swedish public service TV news this evening: "...            b9AcE   
740     Im about to retire. And as I look back, I am r...       frenchcori   
746     I miss Barbara Walters. She's ill and in hidin...          AJDMaru   
750     "#MeToo" -- #ProblematicWomen #RedPillBlack .....   OverTheMoonbat   
751     I know at least a dozen of my friends have men...   JeremyMcLellan   
774     Meghan_charts Dear Future Husband y Better uwu...      EzraFitz_13   
972     "Racism is the norm in our society and sexism ...        NolanHack   
975     Feminism isn't a dirty word and feminists aren...  catladypolitics   
1010    Anyway, a little blog post from yours truly on...   forbiddencomma   
1055    Unlike the abusers, victims don't get out with...      Charmed0504   
1128    2- that every other day another person being a...  

In [110]:
# case #2
tweets[tweets['replyToSN'].isnull() & tweets['text'].str.startswith('@')]

tweetId       screenName  \
200         201    NoHopeCitizen   
205         206        Unitynow8   
544         545    lurvejennifer   
1503       1504         22stacyb   
1786       1787       PattyParas   
2355       2356      justshocked   
2392       2393        roseyrosy   
2863       2864          HYD_MRA   
2991       2992    AlysseStewart   
4039       4040    peasantbarbie   
4188       4189  MinnieM22421364   
4470       4471         Soonfeed   
4565       4566           vooda1   
6870       6871      TheRighting   
7904       7905   _jessicawinter   
8459       8460   oldskoolqueene   
9425       9426          cookerT   
18693     18694  NurseKimberly16   
18728     18729  NurseKimberly16   
24411     24412    Rightwinger65   
27056     27057   augusta_khalil   
34524     34525         kinkel78   
46021     46022            CDB0Y   
49838     49839        AJonkhart   
51770     51771   kaitlyn_graace   
52249     52250         MacMargi   
55885     55886        watchkeep   
58817     58818     Claudia91919   
60475     60476         sbbumpas   
62679     62680        Dasani_01   
...         ...              ...   
317692   317696  AntifaAnchorage   
322521   322525      talithaaax8   
322897   322901     hotcitykitty   
326840   326844       rosanna_lw   
328750   328754     PatriotScoop   
328798   328802   kimmywatkins77   
329736   329740           kkeejj   
331196   331200     shadowdogman   
331391   331395  SuzanneBuchan14   
333972   333976     helenpringle   
335550   335554        phxrocker   
336515   336519     helenpringle   
341934   341938      mike_salter   
343966   343970  HedleyThomasFak   
344937   344941       Nuropsych1   
356207   356211      whythetruth   
356836   356840            CDB0Y   
358758   358762      AltanHoltbo   
360017   360021      AnneBarasso   
363786   363790       ryan_lecce   
364306   364310       ryan_lecce   
364421   364425    CouldBiteDoes   
364434   364438     FionaMcAnena   
364695   364699       Safe4years   
365356   365360         MrtYco0n   
366693   366697      CoxShiloh61   
366895   366899      CoxShiloh61   
375123   375127    dutchschultz2   
382073   382078    Ironyisfunny8   
386155   386160       WiscoRight   

                                                     text replyToSN  \
200     @MLauer picks on @POTUS for a discussion with ...       NaN   
205     @LanaDelRaytheon Also were do I bet on how man...       NaN   
544     @MLauer I'm beside myself with anger and disgu...       NaN   
1503    @MLauer "Fuck, marry, or kill" really? You're ...       NaN   
1786    @Steve4276 @BillOReilly You could be wearing a...       NaN   
2355    @MLauer #creeper how many did you rape?? #MeTo...       NaN   
2392    @MLauer Speaking of facts: Youre out of a job....       NaN   
2863    @MLauer How does #feminism taste now? Not pret...       NaN   
2991    @MLauer Looks like they needed some different ...       NaN   
4039    @ everyone who posted or liked #metoo posts an...       NaN   
4188    @MLauer Another one bites the dust. @MLauer fi...       NaN   
4470    @TimesTalks speaks to actor Ashley Judd and th...       NaN   
4565    @MattlauerToday Karmas a bitch. I wonder if @A...       NaN   
6870    @tullyborland of @TheFederalist1 asks in artic...       NaN   
7904    @@xonecole "Knowing someone you love was assau...       NaN   
8459    @BlackLivesMatter @NOMORE @metoo #metoo DON'T ...       NaN   
9425    @MLauer You intend to give the 30m to your vic...       NaN   
18693   @ngains13 #metoo #wearblack Mourning our loss ...       NaN   
18728   @ngains13 #metoo #wearblack Mourning our loss ...       NaN   
24411   @carmtom13 Whatâ€™s Wrong with the #MeToo Camp...       NaN   
27056   @tobiasbybvaad makes fun of @brianmÃ¸rk attemp...       NaN   
34524   @ayeatman @netflix Mr yeatman do you not belie...       NaN   
46021   @null Two Colleges Bound by History Are Roiled...       NaN   
49838        @Tenhorses4 Waiting for a #metoo from barbie       NaN   


There are 
* 2702 tweets for case #1
* 131 tweets for case #2

Quickly skimming the case #2 of tweets that started with "@" but were not recognized as replies,
- there are some tweets that replied to an account that is/was unavailable
- there are tweets with misformatted replies ("@@..", "@#...", "@ username", "@null")

Let's see if any #2 tweets were also retweets, or retweeted

In [111]:
# none of the tweets that we consider as case #2 were retweeted
# makes sense, as they were intended to be resplies to a particular user (in most cases)
tweets[tweets['replyToSN'].isnull() & tweets['text'].str.startswith('@') & tweets['retweeted'] == True]

Empty DataFrame
Columns: [tweetId, screenName, text, replyToSN, isRetweet, retweeted, retweetCount, favorited, favoriteCount, truncated, created, statusSource, longitude, latitude]
Index: []

In [112]:
# of the tweets that we consider as case #2, 3 of them were also retweets, but also to announce suspension of the user
tweets[tweets['replyToSN'].isnull() & tweets['text'].str.startswith('@') & tweets['isRetweet'] == True]

Empty DataFrame
Columns: [tweetId, screenName, text, replyToSN, isRetweet, retweeted, retweetCount, favorited, favoriteCount, truncated, created, statusSource, longitude, latitude]
Index: []

I'm going to drop these and save the data as V2

Rationale:
- case #1 : Since they were recognized as "replies" by the algorithm, I will assume that these tweets only appeared in the timeline of the recipient, plus anyone that follow both the sender and recipient. Since we are interested in how the movement grew, we will exclude these from V2 dataset
- case #2 : We will also exclude these from V2 dataset since many of them seem to have been falsely labeled as "not a reply"

In [113]:
tweets

tweetId       screenName  \
0             1        ahmediaTV   
1             2   JesusPrepper74   
2             3   DemerisePotvin   
3             4     TheDawnStott   
4             5   scottygirl2014   
5             6     ForEverBrenn   
6             7   silveriaalison   
7             8         calrican   
8             9   traugott_sarah   
9            10  SchifanoRaelene   
10           11      BrunusCutis   
11           12       RDonSteele   
12           13     _standeliver   
13           14         dbehan79   
14           15       european_4   
15           16  FrancescaBiller   
16           17   emilyjoypoetry   
17           18         frozenjo   
18           19         num1_fan   
19           20      DougsMom204   
20           21         page_lie   
21           22  VirginiusPrimus   
22           23       1mimi4ever   
23           24      justshocked   
24           25    ProphetPhella   
25           26   womanontheleft   
26           27        JessLivMo   
27           28          JC4ever   
28           29       european_4   
29           30  collegeclasses5   
...         ...              ...   
393088   393106   writerincanada   
393089   393107    ellimayradrep   
393090   393108  viniciusnikolod   
393091   393109      JamesEFinch   
393092   393110         nscrowba   
393093   393111       book_tribe   
393094   393112         jp_flyer   
393095   393113       ruby_wine_   
393096   393114      DebraRobbin   
393097   393115      StevenGuggs   
393098   393116      PeterFeaman   
393099   393117  Tucs0nMortgages   
393100   393118  tlacovaspravask   
393101   393119      King17Larry   
393102   393120         Rparisee   
393103   393121        Adam_Eire   
393104   393122   mikefreemanNFL   
393105   393123        tomcat159   
393106   393124     Zwoodbutcher   
393107   393125        EINITNews   
393108   393126   AlgerianPalest   
393109   393127    kingofponders   
393110   393128      KosPatricia   
393111   393129     TwittaChicca   
393112   393130   BuffyLibSlayer   
393113   393131       boaomega22   
393114   393132   April_Magazine   
393115   393133         Noofer55   
393116   393134           ZBezzt   
393117   393135         pewdrdad   

                                                     text        replyToSN  \
0         American Harem.. #MeToo https://t.co/HjExLJdGuF              NaN   
1       @johnconyersjr  @alfranken  why have you guys ...    johnconyersjr   
2       Watched Megan Kelly ask Joe Keery this A.M. if...              NaN   
3       Women have been talking about this crap the en...              NaN   
4       .@BetteMidler please speak to this sexual assa...              NaN   
5       We can't keep turning a blind eye and pretend ...              NaN   
6       Jay-Z is saying what I've been saying. DJT's j...              NaN   
7       Where in the world is @MattLauer Celebrate #MeToo              NaN   
8              @JoyAnnReid Keep it coming ladies!  #MeToo       JoyAnnReid   
9       @RepAdamSmith Workplace is one place, but what...     RepAdamSmith   
10      Is it just me or does the #MeToo <----icon; fr...              NaN   
11      Just  got scammed out of  $25.  Bought #TigerW...              NaN   
12      @RepKathleenRice @RepJayapal Calling out @RepJ...  RepKathleenRice   
13                   #BlackLivesMatter with #MeToo yup ok              NaN   
14      Why are not the men haters from #Metoo marchin...              NaN   
15      I was sexually harassed as a "young Intern" fo...              NaN   
16      So I have a question. This post was published ...              NaN   
17      Im pretty sure @DanRather and Brian Williams a...              NaN   
18      Aint trying to start nothing but wouldnt it be...              NaN   
19      How can @realDonaldTrump talk about anyone tha...              NaN   
20      Yes!! WHEN it happens to you, THEN you can dec...              NaN   
21      @CNN Read: "we must destroy the oppressive pat...  

In [114]:
dropped = tweets[np.logical_not(tweets['replyToSN'].isnull()) != tweets['text'].str.startswith('@')]

In [115]:
len(tweets)
tweets.drop(tweets[np.logical_not(tweets['replyToSN'].isnull()) != tweets['text'].str.startswith('@')].index, inplace=True)
len(tweets)

393118

390288

Original: 393135 rows<br>
V2: 390302 rows

In [116]:
tweets.to_csv('Data/tweets.csv', index=False, encoding='utf-8')

We will also have to update the other data sets to reflect the change

In [117]:
dropped

tweetId       screenName  \
34           35      ThalesLives   
105         106   LilMissRightie   
200         201    NoHopeCitizen   
205         206        Unitynow8   
229         230      EzraFitz_13   
308         309       frenchcori   
359         360            b9AcE   
390         391  Webbedspiderrob   
391         392        ejgibbens   
426         427        StuckonSW   
485         486   BooksbySSJaxon   
544         545    lurvejennifer   
549         550       AnaMardoll   
578         579   TobsonHelsinki   
647         648            b9AcE   
740         741       frenchcori   
746         747          AJDMaru   
750         751   OverTheMoonbat   
751         752   JeremyMcLellan   
774         775      EzraFitz_13   
972         973        NolanHack   
975         976  catladypolitics   
1010       1011   forbiddencomma   
1055       1056      Charmed0504   
1128       1129     WilliarMedic   
1276       1277    CrankyOldBats   
1356       1357    ktullymcmanus   
1431       1432    mauraacarroll   
1434       1435      yrfatfriend   
1490       1491   chelliepingree   
...         ...              ...   
389372   389378    peterhoneyman   
389536   389542         VVandvik   
389744   389754  ScholarNagaMama   
389825   389837      MrGCampbell   
389827   389839      MrGCampbell   
389990   390003  JonathanAconomy   
390125   390138      EzraFitz_13   
390353   390366      EzraFitz_13   
390483   390496   XhN_XvieR_XyZa   
390558   390571       laurenbaer   
390693   390706        AnneArdon   
391448   391466      EzraFitz_13   
391552   391570      EzraFitz_13   
391587   391605    TheGamblingQB   
391634   391652        GitGirl89   
391678   391696            Que3M   
391703   391721       JGibsonDem   
391742   391760  NicoleScioville   
391817   391835    SarahSchwartz   
391843   391861         HillYes1   
391868   391886      xkristi_kat   
392022   392040   NewEnglander34   
392323   392341   Mike4LibertyTX   
392403   392421      victorymonk   
392544   392562  UncleChanBlake2   
392685   392703       lucyoopsie   
392692   392710     JackPolakoff   
392696   392714       lucyoopsie   
392968   392986      EzraFitz_13   
392977   392995  DiederikKramers   

                                                     text        replyToSN  \
34      8. But how soon before this snowball of sexual...      ThalesLives   
105     Forget #MeToo for now or for just a moment and...   LilMissRightie   
200     @MLauer picks on @POTUS for a discussion with ...              NaN   
205     @LanaDelRaytheon Also were do I bet on how man...              NaN   
229     RT lucas_megatron: Meghan_Trainor just this On...      EzraFitz_13   
308     #MeToo reminds me of that awkward, uncomfortab...       frenchcori   
359     Astonishing that AFAIK, there hasn't been any ...            b9AcE   
390     For most of these accusations, there is little...  Webbedspiderrob   
391     Next up on the #metoo playlist - Fuck You by L...        ejgibbens   
426     America: The #MeToo movement has been a waters...        StuckonSW   
485     For we cannot tarry here; We must fight my dar...   BooksbySSJaxon   
544     @MLauer I'm beside myself with anger and disgu...              NaN   
549     I'm just incredibly tired of people saying "oh...       AnaMardoll   
578     I wondered how long it would take for Finnish ...   TobsonHelsinki   
647     Swedish public service TV news this evening: "...            b9AcE   
740     Im about to retire. And as I look back, I am r...       frenchcori   
746     I miss Barbara Walters. She's ill and in hidin...          AJDMaru   
750     "#MeToo" -- #ProblematicWomen #RedPillBlack .....   OverTheMoonbat   
751     I know at least a dozen of my friends have men...   JeremyMcLellan   
774     Meghan_charts Dear Future Husband y Better uwu...      EzraFitz_13   
972     "Racism is the norm in our society and sexism ...        NolanHack   
975     Feminism isn't a dirty word and feminists aren...  

In [118]:
associations[associations['tweetId'].isin(dropped['tweetId'])]

Empty DataFrame
Columns: [associationId, tweetId, screenName, associationType, keyword]
Index: []